### ISSUE TITLE
K4/1 feladat 

### ISSUE THREAD

**Issue by nkrisztina** [PE-MK-JAKI-H/MHFGY#10]
Kedves Tanár Úr!

Segítséget szeretnék kérni a K4/1-es feladat ábráival kapcsolatban,mivel ezen a ponton megakadtam. Megnéztem a moodle-be feltöltött wolframos részt és dokumentumot, viszont így se tudom hogyan kezdhetnék neki.

Válaszát előre is köszönöm!

**Comment by Szalay** [comment]
A Moodle-be töltöttem fel egy újabb leírást, ezúttal a hődiagram készítésről. Ezen látod, hogy víz esetén hogyan készül a diagram. Ammónia esetén alapvetően ugyanilyen lesz. Amennyiben nem sikerül az adatelőállítás, akkor írd meg, hogy pontosan milyen görbék adatait szeretnéd, és kimentem neked. Így tudsz haladni az ábrával.

**Comment by nkrisztina** [comment]
Kedves Tanár Úr!

Próbálkoztam az adatkinyeréssel, de sehogy se sikerül rendesen hogy jussak is eredményre. Kérem mentse ki nekem a K4/1-es feladathoz tartozó ammónia közvetítő közeggel dolgozó körfolyamat T-s diagram adatait, valamint a hűtőgép körfolyamat lgp-h adatait.

Segítségét előre is nagyon köszönöm!

**Comment by Szalay** [comment]
Ennél egy kicsit pontosabb meghatározást kérnék. Milyen fajta görbéket, mekkora értékhez tartozzanak, hőmérsékletben vagy nyomásban mettől meddig tartson az adatsor.

**Comment by nkrisztina** [comment]
![k41_TS](https://user-images.githubusercontent.com/63298831/81486493-6c980900-9255-11ea-8068-a45a08e442ff.jpg)

Lerajzoltam a Ts diagramot és odaírtam mellé az adatokat, amiből szeretném az adatsort.

Illetve feltöltöttem GitHubra az eddig elkészült munkámat. Szeretném megkérdezni, hogy ez hány százalék eddig? 
Neptunkódom: CLCWJ1

**Comment by Szalay** [comment]
Apróbb hiba és hiányosság van elég sok, de az elégséges szintet már a jelenlegi állapotában is eléri a beadandó. Ha szeretnéd még javítani, akkor írok részletes listát.

A T-s diagramot kérném legalább részben elkészíteni. A szükséges adatfájlokat csatoltam

[nh3_p1.9.txt](https://github.com/PE-MK-JAKI-H/MHFGY/files/4608309/nh3_p1.9.txt)
[nh3_p10.txt](https://github.com/PE-MK-JAKI-H/MHFGY/files/4608310/nh3_p10.txt)
[nh3_ts.txt](https://github.com/PE-MK-JAKI-H/MHFGY/files/4608311/nh3_ts.txt)

**Comment by nkrisztina** [comment]
Köszönöm, hogy megnézte és az adatsorokat is! Szeretném javítani a hibákat!

**Comment by Szalay** [comment]
1) A feladat címében hiányzik egy szóköz.
2) A b) pontnál a Pelm-ben az elm nem alsóindex.
3) Az epszilont a `\varepsilon` paranccsal szedd!
4) A pontok nagyrészt fölöslegese (mint szorzásjelek).
5) A 4.12-13 körül is az `\SI`-vel legyenek a mértékegységek!

Általánosságban kicsit több szöveges magyarázat kellene az egyenletek közé.

És természetesen a T-s diagram hiányzik még, amin a rács ne maradjon rajt a végén!

**Comment by nkrisztina** [comment]
<img width="959" alt="probléma" src="https://user-images.githubusercontent.com/63298831/81740465-4bc1f480-949d-11ea-8fef-ce26f1302c42.png">
Elkezdtem a ts diagram ábrázolását, viszont felmerült egy probléma. Az x-tengelyt már sikerült leállítanom az y-hoz képest, hogy közös pontból induljanak. Ennek következtében viszont a tengely feliratai hibás helyen vannak. Már nagyon sok variációt próbáltam,de még mindig nincs jó helyen. Tudna segíteni benne?

**Comment by nkrisztina** [comment]
Befejeztem a Ts diagram rajzolását, a felsorolt hibákat pedig javítottam. Az aktuális anyagot feltöltöttem Githubra. 
Szeretnék érdeklődni, hogy kell-e még valamit változtatnom a végső leadás előtt?

**Comment by Szalay** [comment]
Pontoztama beadandót. Az eredményt megtalálod a Google-táblázatban. A nyomás-hőtartalom hiányzik, de a 75 pontos rész elég jó. Maradtak apróbb hibák, de mivel jegyen nem változtat, ezért nem javíttatom ki őket.

**Comment by nkrisztina** [comment]
Köszönöm szépen és a sok segítséget is!
