### ISSUE TITLE
HS 32 // HS 5 feladatok

### ISSUE THREAD

**Issue by kovacsmiklos** [PE-MK-JAKI-H/MHFGY#11]
Tisztelt Tanár Úr!
Letudná ellenőrizni a feladataim megoldásait?

![HS5 1](https://user-images.githubusercontent.com/63108137/79567586-c83b0080-80b4-11ea-85ba-8d37a8bc5c07.jpg)
![HS5 2](https://user-images.githubusercontent.com/63108137/79567592-ca9d5a80-80b4-11ea-85f2-4382cb6c7e5c.jpg)
![HS32 1](https://user-images.githubusercontent.com/63108137/79567605-d0933b80-80b4-11ea-9eed-4b6011f00b5a.jpg)
![HS32 2](https://user-images.githubusercontent.com/63108137/79567610-d25cff00-80b4-11ea-891f-e325098f9800.jpg)

**Comment by Szalay** [comment]
HS5: 
1) Hengeres falnál lineáris hőáramsűrűség van. A jelölés \dot{q}_{lin} legyen.
2) a lineáris hőáramsűrűséget az átmérőkkel írod fel, de aztán a sugarak értékei helyettesíted be. Rejtett hiba, mert a végeredmény számértéke jó így is.
3) A réteghatár-hőmérsékletek számítása rendben van, de az átrendezett alakok majd kerüljenek be a dokumentumba. Kerekíteni nem kell, 3 tizedesjegy pontosság ezeknél az értékeknél megfelelő.
4) A hengeres falakban nem lineáris a hőmérséklet-eloszlás. Ez hiba az ábrán. Ráadásul a számításos részben éppen ezeknek a görbéknek az egyenleteit használod.
5) Kisebb jelentőségű, de a feladat nem közöl semmit a falon kívüli hőmérséklet-viszonyokról, ezért ott ne rajzold meg az eloszlást.
6) Ha hőmérséklet-hely függvény ábrázolását kiegészíted a réteghatárokkal, a hővezetési tényezőikkel és a méreteikkel, akkor nem kell két külön ábrát készíteni.

**Comment by Szalay** [comment]
HS32: 
1) A vízértékek W/K-ben kellene kijöjjenek, de nem csak az erdményük rossz, hanem a számítás is.
2) A különbség értékeket nem kis hanem nagy deltával szokták jelölni.
3) A többi eredmény helyes, mert a vízértékek 1000-szeres hibája valahol egy kilo előlatg visszaírásával vagy elhagyásával kiegyenlítődik.
4) A feladat nem kért ábrát, de nem baj ha van.
3)

**Comment by kovacsmiklos** [comment]
Köszönöm szépen! Kijavítottam a hibákat, így helyesek Tanár Úr? 
![1](https://user-images.githubusercontent.com/63108137/79690106-0bce6f80-8259-11ea-8d2a-0bea9acc04d9.jpg)
![2](https://user-images.githubusercontent.com/63108137/79690110-0cff9c80-8259-11ea-880b-c892d4a5ac9a.jpg)
![3](https://user-images.githubusercontent.com/63108137/79690115-0ec96000-8259-11ea-83d0-c82167f16f55.jpg)

**Comment by kovacsmiklos** [comment]
Közben észre vettem, hogy a vízértékek mértékegységébe nem Kelvint írtam.

**Comment by Szalay** [comment]
Úgy tűnik, most jók az értékek, a kelvint leszámítva.

**Comment by kovacsmiklos** [comment]
Köszönöm szépen.

**Comment by Szalay** [comment]
Átnéztem a két feladatot és összeírtam a javítandó hibákat:

**HS5**
1) A feladat száma és **címe** legyen elöl, ezután legyen a táblázat!
2) Az AC alsóindex és T, mitn a hőmérséklet jel legyen nagybetű!
3) A (6.15)-ös egyenletben a nevezőben a logaritmusoknál szükségtelen a zárójel. Ha viszont mégis van, akkor `\left( ... \right)` párral legyen szedve!
4) Az a/b/c részekben még néhány helyen van fölösleges zárójel, de egyéb hibát nem látok.
5) A d) részben a hőmérséklet-hely függvény rossz, nem lehet szakadása, javítani kell. A színválasztás, bár másodlagos, nem a legjobb. A belső és a külső réteg körvonalai legyenek vastagok (ultra thick).

Az ábra ennél a feladatnál különálló 25 pontos rész, úgyhogy ki kell javítani.

**HS32**
1) A HS5-nél leírtak itt is érvényesek.
2) A pontok címei legyenek mind nagybetűvel kezdve!
3) A feladatleírásban a három pontok ne legyenek, "a" vagy "az" legyen helyettük.

A fentieket leszámítva ez a feladat rendben van.

**Comment by kovacsmiklos** [comment]
Tanár Úr! 
Megtudná mondani, hogy a beadandóm elfogadható-e? 
Válaszát előre is köszönöm.

**Comment by Szalay** [comment]
Átnéztem, pontoztam, az eredményt megtalálod a Google-táblázatban.
