### ISSUE TITLE
K2/3 Rankine_Clausius_körfolyamat

### ISSUE THREAD

**Issue by VeiglerZita** [PE-MK-JAKI-H/MHFGY#12]
![9](https://user-images.githubusercontent.com/63042751/79664371-6d3d0280-81b5-11ea-93f0-14612f338464.jpg)

![1](https://user-images.githubusercontent.com/63042751/79664063-572f4200-81b5-11ea-8a5d-2192f5cd7884.jpg)
![2](https://user-images.githubusercontent.com/63042751/79664080-58606f00-81b5-11ea-8643-233aa737868b.jpg)
![3](https://user-images.githubusercontent.com/63042751/79664096-59919c00-81b5-11ea-9619-e2d3be77b701.jpg)
![4](https://user-images.githubusercontent.com/63042751/79664105-5a2a3280-81b5-11ea-9863-311e6ef941ae.jpg)
![5](https://user-images.githubusercontent.com/63042751/79664122-5b5b5f80-81b5-11ea-84d2-7affb2e9228c.jpg)
![6](https://user-images.githubusercontent.com/63042751/79664137-5c8c8c80-81b5-11ea-9bd8-631b66c58fb0.jpg)
![7](https://user-images.githubusercontent.com/63042751/79664152-5dbdb980-81b5-11ea-8bac-a3670d88c255.jpg)
![8](https://user-images.githubusercontent.com/63042751/79664177-5f877d00-81b5-11ea-9542-8fc543aa61a9.jpg)

**Comment by Szalay** [comment]
Ellenőriztem a feladatot, miután megtaláltam, hol kezdődik :)

1) A munka jele w nem omega.
2) Az elektronikus változatban a jelöléseket az óraihoz kellene majd igazítani. A hőtartalom h legyen,  a kazánnyomás p_K, lecsapódási nyomás p_L.
3) A részkörfolyamatokat lehet jobb lenne betűvel jelölni.
4) Az első oldal számításai már leellenőriztem, és rendben voltak az összefdüggések és a számértékek is, de egy kérdésem van: a h_4'' honnan jön?

Illetve lenne még egy kérdésem: a feladat kétemberes, ez csak a te munkád, vagy közösen dolgoztatok?

A diagramok mindegyikét nem kell elkészíteni. Egy nagy adatalapú T-s diagramot kérek a teljes és egyet a részkörfolyamtokról, illetve a szivattyús részről egy torzított ábrát (a valós adatokkal rajzolva nem látszana semmi). H-s diagram nem kell, a feladat enélkül is elég összetett.

Az elektronikus változat követheti a feladatgyűjtemény felépítését, de az indokolatlan rövidítések, idegen szavak és egyéb igénytelenségek nélkül.

**Comment by VeiglerZita** [comment]
Bocsánat én a dupla w-t úgy írom, mintha omega lenne. Rendben, akkor a jelöléseket átírjuk, köszönjük! A h4 le van vezetve, h_4''-t h_0''-nek vettük, mivel ugyanazon a vízszintes görbén helyezkednek el. Köszönjük a válaszokat!
Igen, ketten dolgoztunk rajta, együtt oldottuk meg, csak mivel én szebben írok, én írtam le.

**Comment by VeiglerZita** [comment]
Tanár Úr!
A szivattyús diagramnál van egy olyan problémánk, hogy nem tudjuk, hogyan kell eltorzítani a diagrommon a tengelyek értékét, hogy ne a valós értékekkel számoljon. Mi az RC T-s diagramból indultunk ki. 
Köszönjük válaszát!

**Comment by Szalay** [comment]
Ha szivattyús ábrát T-s diagramban rajzoljátok, akkor jó megoldás lehet az állapotváltozás körüli rész kinagyítása. Az ábrázolt tartomány és a tengelyfeliratokat kell jól megválasztani.
