### ISSUE TITLE
2/MH20

### ISSUE THREAD

**Issue by rezibence** [PE-MK-JAKI-H/MHFGY#13]
Tisztelt Tanár Úr!
Szeretném kérni hogy amennyiben ideje engedi legyen szíves átnézni mielőtt beviszem latexbe.
Tisztelettel és Köszönettel: Rezi Bence
[qwp76t_mh_20.pdf](https://github.com/PE-MK-JAKI-H/MHFGY/files/4498814/qwp76t_mh_20.pdf)

**Comment by Szalay** [comment]
Megnéztem a megoldásod, és sajnos komoly problémák vannak vele. A számítás sincs rendben és a T-s diagram sem felel meg a feladatban leírtaknak. 

1) A zárójelben megadott munka hányados és P_{sziv} teljesítmény a megoldás, nem adat. Ezeknek kellene kijönni a feladatból
2) A szöveg megadja, hogy 200 bar kazánnyomáson 600 °C-ig hevítik a gőzt. Egy netes T-s diagramból (pl. ez, amit a hőtan moodle-jében is megadtam: http://entes.kr/Sub/Diagram%20Ts/Steam%20Ts%20.htm) gyorsan lehet ellenőrizni, hogy ez a pont a légnemű fázisban van, azaz a körfolyamat túlhevítéses. A T-s diagramod nem ilyen.

Szóval a feladat megoldást újra át kell gondolni.

**Comment by rezibence** [comment]
Köszönöm szépen!
Újraszámolom köszönöm a segítséget!
Tisztelettel és Köszönettel Rezi Bence

Szalay <notifications@github.com> ezt írta (időpont: 2020. ápr. 22., Sze
14:10):
