### ISSUE TITLE
Véglegesnek szánt beadás

### ISSUE THREAD

**Issue by rupiman97** [PE-MK-JAKI-H/MHFGY#14]
Jó napot tanár úr!

Úgy gondolom, hogy a feladatommal végeztem, az ön által hozzászólásba írt hibákat kijavítottam.
Legyen szíves átnézni, ha ideje engedi.

Köszönöm szépen!

**Comment by Szalay** [comment]
Ellenőriztem, és tényleg elég jól állsz a feladat megoldásával, viszont szerintem vagy nem javítottál ki mindent vagy sikerül újabb hibákat bevinni. Mindegy is, újra leírom, hogy mivel van probléma. Mivel egyik sem túlzottan komoly, nem okozhat gondot a javításuk:
1) Az első egyenletben az a const legyen állandó, vagy legalább áll. Az egyenletbe \textrm{}-mel tudsz betennni sima szöveget. Mellette a dv-t \dif v-vel csináld, \dif a differenciált jelölő d.
2) Az ábrákon lévő számértékekben tizedes pontok vannak. Legyenek ezek is tizedes vesszők.
3) Az alcímek végén ne legyen kettőspont, ez a c)-re és a d)-re vonatkozik, és a c) címe "A szükséges hő számítása" legyen. A d) címe legyen "Az állapotváltozás $T-s$ és $p-v$ diagramban". A b)-nél az alpontok elé nem kellenek a kötőjelek.
4) Az kétvesszős értékeket ne egy ", hanem kettő '' jelölje.
5) Az első három egyenletnél a 0 értékekhez is tartozik mértékegység.
6) A második egyenlet c_V-s része csak ideális gázra igaz.

Lehetséges, hogy nem töltötted fel a javított változatot? Szerintem ugyanezeket írtam fel legutóbb is.

Ezeken felül:
1) A T-s diagram fázishatár-lekérdezését órán elrontottam, a teteje ezért lapos. Időközben ezt kijavítottam, és egy fájlba mentettem a helyes adatsort. A két rosszat cseréld ki a csatolt ts.txt-re.
[ts.txt](https://github.com/PE-MK-JAKI-H/MHFGY/files/4518642/ts.txt)

És még ezen felül: a feladat csak 75 pontos, viszont mivel elég jól megcsináltad, talán van motivációd arra, hogy javíts még kicsit rajta. Ehhez a következő két módosítást kellene még elvégezni:
1) A b) pontban egy-egy mondatban leírni, hogy hogyan állítottad elő az adatokat (mi ismert, ez alapján mit lehet meghatározni). Egyébként leellenőriztem őket a Wolfram adatai alapján helyesek.
2) A csatolt ts_v0699.txt-t is ábrázolni a T-s diagramon, ez a teljes izochor vonalat fogja adni. Legyen piros, és a hozzá tartozó v értéket is írd mellé. Ideális esetben pontosan egybeesik az általad már ábrázolt állapotváltozással.
[ts_v0699.txt](https://github.com/PE-MK-JAKI-H/MHFGY/files/4518983/ts_v0699.txt)

**Comment by rupiman97** [comment]
Köszönöm az átnézést! A hibákat kijavítottam, és feltöltöttem a megoldást az ágamba.

**Comment by Szalay** [comment]
Leellenőriztem. A két kért módosítás miatt a feladat pontszámát megöveltem 100-ra. Már csak apróbb fogalmazási és jelölési hibák maradtak, illetve kicsit bővebb elírást vártam a b) részhez, de így is 92 % az eredmény. A pontozást a Google-táblázatban megtalálod, a szempontokat pedig a Moodle-ben.

**Comment by rupiman97** [comment]
Köszönöm szépen!
