### ISSUE TITLE
2/MH14. és 15 .

### ISSUE THREAD

**Issue by smisia** [PE-MK-JAKI-H/MHFGY#15]
Tisztelt Tanár Úr!

Amennyiben van rá lehetőség át tudná nézni, hogy az eddigi számításaim helyesek-e?

(Az MH 15. feladat utolsó részében a munka számolásánál sajnos elakadtam mivel az adiabatikus reverzibilis expanzióra több képletet is találtam (nem ideális gázokra) de egyenlőre sajnos egyiket sem tudtam megfelelően hasznosítani.)

Köszönettel,
Somodi Mihály

![20200423_210455](https://user-images.githubusercontent.com/63014443/80139310-8cb5a000-85a6-11ea-82ed-e79afb1d2aaa.jpg)
![20200423_210510](https://user-images.githubusercontent.com/63014443/80139315-8fb09080-85a6-11ea-89b6-1c61cb594c8e.jpg)
![20200423_210520](https://user-images.githubusercontent.com/63014443/80139689-241af300-85a7-11ea-8b74-c98d6b617eb7.jpg)
![20200423_210539](https://user-images.githubusercontent.com/63014443/80139701-28471080-85a7-11ea-863b-02dcc4782258.jpg)

**Comment by Szalay** [comment]
Az MH14 rendben van, helyesek a lépések és az eredmények is. A feladatkiírás mellett a gőztáblázati adatok szükségessége a fajtérfogat szélsőértékekre vonatkozott, amit a feladat meg is adott. Azért írtam fel, hogy ellenőrizve legyen. A táblázat ezért nem szükséges ennél a feladatnál.

**Comment by Szalay** [comment]
Az MH15-tel van néhány gond. 
1) A víz nem ideális gáz, ezért a technikai munka számítását nem csinálhatod az ideális gázra vonatkozó összefüggés szerint.
2) A feladat a 28 baros kezdeti állapotot jelöli 1-es, az 1 baros végállapotot 2-es ponttal, a megoldásodban viszont a nyomás alapjá nszámoztál, ami miatt a 2-es az 1-es pont :)
3) A \Delta s-nél elég nagyot kerekítettél, de a feladatgyűjtemény is.
4) A feladat legelején kellene majd magyarázatot írni, hogy mit miért csinálsz.
5) A tömeg számítása nem jó, a gőz térfogatát a cseppfolyós víz fajtérfogatával osztod. Látom, hogy kijött az érték, amit feladatgyűjtemény megad, de ez így akkor sem jó.

A feladat elején a következő lépéseket kellene követni:
1) kiszámolni h_1-et, figyelembe véve h_1''-t is, az MH14 szerint x-szel (kicsit több lesz, mint 990).
2) kiszámolni az így kapott h_1-gyel x_2-t (kicsit nagyobb lesz 0,254-nél).
3) a teljes eredeti tömeget és az új fajlagos gőztartalmat alapul véve számolni a keletkező gőz tömegét.
