### ISSUE TITLE
HS 33 ellenőrzésre szánva

### ISSUE THREAD

**Issue by muha64** [PE-MK-JAKI-H/MHFGY#16]
Kedves Tanár Úr!

Amennyiben lesz ideje vetne egy pillantást a munkámra?(irvuyq)
Köszönöm szépen!

**Comment by Szalay** [comment]
A következő beküldésnél az MHFGY.tex-et és a pdf-et is pipáld be, ne csak a saját feladatod fájlját!

A számítás menete és a számértékek helyesek,

**Comment by Szalay** [comment]
Két dologgal ki kellen3 még egészíteni a kidolgozást:
1) Meg kellene említeni, hogy mi az LMTD, és az itt mennyi.
2) Az egyenletek közötti magyarázatokat kicsit lehetne bővíteni.

**Comment by muha64** [comment]
Rendben. Kiegészítem és újra helyesen feltöltöm!

**Comment by muha64** [comment]
Kedves Tanár Úr!
Feltettem a kiegészített verziót. Remélem ez így megfelelő lesz. Ha végeztem, akkor pull request-elnem kell vagy maradhat a munkám úgy , ahogy van?

**Comment by Szalay** [comment]
Egyelőre nem kell pull request.

**Comment by muha64** [comment]
Rendben, köszönöm. Akkor beadottnak tekintem a munkámat.

**Comment by Szalay** [comment]
Amiket ide írtam, azokat továbbra is javítani kellene: https://github.com/PE-MK-JAKI-H/MHFGY/commit/5ef8c8a7ddca064f3927bb1c27811019aa781b4a

**Comment by muha64** [comment]
Rendben. Javítom!

**Comment by muha64** [comment]
Javítottam mindent, ami kimaradt.

**Comment by Szalay** [comment]
Átnéztem újra, 
1) A szövege magyarázatban T(A) is legyen egyenlet, az egyik mondat előtt, illetve a "vég-" után hiányzik egy szóköz.
2) A T_{2v}-t elszámoltad. Vagy elírtad, mert az ábrán jó.
3) A b) pont címe végén a zárójel és a szóköz fel van cserélve.
4) Az LMTD-t rosszul csináltad, illetve túl bonyolítottad. De nézzük a bonyolult utat: a \DeltaT szerepel a nevezőben is, a logaritmusban, ahol a \DeltaT/\DeltaT = 1 => ln1 = 0, azaz nullával osztasz, és a számlálóban is 0 van, azaz it 0/0-s határértéket kellene meghatározni. Az egyszerű út szerint mindenhol \DeltaT a hőmérséklet különbség, így ez egyben a közepes érték is.
5) A (7.28) előtti mondatvab van egy elszabadult k betű :)

A feladat szinte kész van, ezért le is pontoztam. A fenti javítások után él a pontszám, amit a Google-táblázatban találsz.

**Comment by muha64** [comment]
Javítottam :D .  A 4.-nél mindkét értelmezést leírtam.

**Comment by Szalay** [comment]
Az 1. pont ból a T(A)-t és a hiányzó szóközt még nem javítottad ki. Ettől függetlenlenül a feladato befejezettnek tekintem, de ha az időd engedi, azért javítsd ki ezeket is! Pull request nem kell, az összefésülést majd később megcssinálom én.
