### ISSUE TITLE
Ellenőrzés

### ISSUE THREAD

**Issue by simiivett** [PE-MK-JAKI-H/MHFGY#17]
Tisztelt Tanár Úr!

Meg szeretném kérdezni, hogy jó-e a feladat megoldásom, illetve az ábrát meg tudná-e tekinteni?

Tisztelettel: Simon Ivett (j9o6i0)

**Comment by Szalay** [comment]
Ellenőriztem a kidolgozást. Elég jó állapotban van, de vannak még benne hibák. Ezeket megjegyzésekben hozzáírtam a forráshoz.

**Comment by simiivett** [comment]
Köszönöm szépen a hozzászólásokat, javítom, amit kell!

**Comment by simiivett** [comment]
Javítottam a hibákat, legyen szíves megnézni, ha ideje engedi!
Előre is köszönöm!

**Comment by Szalay** [comment]
A commitból most is kimaradt az MHFGY.tex és a lefordított PDF.

**Comment by Szalay** [comment]
A feladat elején a táblázat a feladat címe és a feladat leírás között legyen!
