### ISSUE TITLE
Feltöltött első verzió (mdpm86)

### ISSUE THREAD

**Issue by fromhun** [PE-MK-JAKI-H/MHFGY#18]
Tisztelt Tanár Úr!

Feltöltésre került 50 pontos hőtan feladatom kérem ellenörzését.

Továbbá második feladatnak kiválasztottam a 6/5-ös feladatot. Itt a Nusselt féle differenciálegyenletnek a problémára adott levezetését látom, ha jól értelmezem.  Ebben szerepel egy lambda hővezetési tényező. Előző feladatoknál a munkafüzetben ha jól láttam anyagi jellemzőként van megadva. Itt a csőfal két oldalán lévő hőmérsékletkülönbség alapján kéne visszaszámítanom a hengeres falon történő hőátszármaztatás esetében érvényes egyenletekkel?  Amennyiben igen a hőáramsűrűséget, hogy tudom kiszámítani? 

Kösözönöm válaszát és segítségét: Vasáros Mátyás

**Comment by Szalay** [comment]
Ellenőrzöm a feladatot és a megjegyzéseket a forráshoz írom a megfelelő beküldésekhez.

**Comment by Szalay** [comment]
A 6/5-ösnél az l a \lambda :) de csak a mértékegység buktatja le. A hőáramsűrűséget egyáltalán nem kell számolni, csak be kell ehlyettesíteni a megadott összefüggésekbe a megadott adatokat.

**Comment by Szalay** [comment]
Az \eta-t pedig átírhatod Pa s-re.

**Comment by fromhun** [comment]
Így már érthető köszönöm a válaszokat és a javítást.

**Comment by fromhun** [comment]
A hibákat javítottam a 6/5-ös feladat pedig elkészült. Köszönöm.

**Comment by Szalay** [comment]
A 6/5-ösben csak néhány apróbb hiba van, ezeket ide írtam: https://github.com/PE-MK-JAKI-H/MHFGY/commit/872e73da6420fe29b48fe19a90396973c3be5bf7

A HS13-ban:
1) A feladat szövegében a stacioner helyett inkább állandósult legyen.
2) Az 5.31-es egyenlet elfér egy sorban, úgyhogy legyen inkább úgy.
3) Az utolsó egyenlet előtt hivatkozol az 5.28-ra, itt a hivatkozás legyen zárójelben, és az egyenlet címkéjében is legyen benne a Neptun-kódod, valahogy így `... (\ref{e:mdpm86_elso}) ...`.

A feladatokat pontoztam is. A fenti hibák javítása után él az eredmény, amit a Google-táblázatban találsz. Ha esetleg ötöst szeretnél kapni, akkor még egy 25 pontos feladatot meg kellene csinálni.

**Comment by Szalay** [comment]
Úgy látom idő közben javítottad a hibákat, csak nem kértél újra ellenőrzést. A 71%-os eredmény él. Ezt az issue-t pedig lezártam.
