### ISSUE TITLE
Feladat ellenőrzésre feltöltve (papeeria-t használok)

### ISSUE THREAD

**Issue by kovacsbence3** [PE-MK-JAKI-H/MHFGY#19]
Tisztel Tanár Úr!
HS1 illetve HS2 feladataomat feltöltöttem, valamint befűztem a saját tárolómban lévő MHFGY.tex fájlba. Szeretném kérni ezeknek az ellenőrzését. Mit változtassak vagy javítsak rajta? Illetve amennyiben megfelelő, kérem ezt is jelezze. 

papeeria-t használok az asztali verziók helyett ebben nem találtam a commit -> push origin lehetőséget.

Kovács Bence
IVZ722

**Comment by Szalay** [comment]
A Papeerián Sync Now gomb van.

![image](https://user-images.githubusercontent.com/8204804/80416113-e1715780-88d3-11ea-91a5-5053cc707b98.png)

**Comment by Szalay** [comment]
Természetesen a saját ágaddal kell szinkronizálni.

**Comment by kovacsbence3** [comment]
Jaaaa, ez a része megvan, fel van szinkronizálva ide GitHub-ra, csak azt hittem a "commit -> push origin"-al lehet kérni az ellenőrzést is egyben az asztali verziónál.
Szóval akkor, a szinkronizálás megvan, HS1 (rajzzal együtt) illetve HS2 fájl (csak a számolás) a saját tárolóm neptunkódos mappájában, illetve ezek "input" parancsal behivatkozva a saját MHFGY.tex fájlomba. Ezekre szeretnék egy ellenőrzést kérni. Kell-e változtatnom, és ha igen mit, hogy le adhassam őket?

**Comment by Szalay** [comment]
Nos, elkezdtem ellenőrizni a feladataid, de az első probléma, hogy nem fordul le. Nem nagy hibákról van szó, de azokat többszörösen sikerült elkövetni. Ha több betűs alsó indexet akarsz, akkor kapcsos zárójelekkel kell csoportosítani a betűket:
`\lambda_{AC}`
Illetve ha már előjött az alsóindex, akkor azt kérném, hogy az egy-két betűs alsóindexek nagybetűk legyenek. 
Ahol szó szerepel alsóindexben, ott pedig a \textit-et használd. Ennek van egy olyan járulékos haszna, hogy az ékezetes betűket is szereti.
`\lambda_{\textit{vízkő}}`

Helyenként vannak fölösleges behúzások a forásban, szóközök, tabulátorok keveredve.

Az \SI{}{} parancsnál sokhelyen írtál egy fölösleges kapcsol zárójelet a végére (\SI{}{}}), ez az egyik oka anank, hogy nem fordul le. A Papeeria fordítója ezt elviseli?

A közepes hőmérséklet jele T_K legyen.

Az alósindex és mértékegység hibákat javítsd, és megnézem újra.

**Comment by kovacsbence3** [comment]
Az alsó indexeket átírtam, illetve a }}-eket is javítottam, már csak a \frac függvény esetén van }} a kódban, ha egyszerre záródik, a \SI illetve a frac is (nemtudom ez probléma-e). A közepes hőmérsékletet átírtam T_K-ra illetve vízkövet is textit-el.

**Comment by Szalay** [comment]
Ilyen előfordulhat, hogy két bemenet ugyanott ér véget, ez nem hiba, mert ilyenkor mindegyik záró zárójelnek van egy nyitó párja. A lényeg az, hogy a zárójelek párosával legyenek.

**Comment by kovacsbence3** [comment]
Így már feltöltésre alkalmas a feladat? mit javítsak benne?

**Comment by Szalay** [comment]
Mivel sok apró beküldésed van, ezért inkább itt írok egy egybefüggő listát a javítandó részekről.
**HS1**:
1) A feladat szövegében vannak apróbb hibák: hiányzó vessző, "fok". A szövegben csak a mennyiségek jelei legyenek, a számértékek külön, ahol most azt írod, hogy Adatok. Az ezt követő egyenlet legyen külön equation*.
2) A feladat szövegét válaszd el a megoldástól, erre jó egy \hline, vagy egy \subsubsection*{Megoldás}.
3) Hőáramsűrűség, nem csak áramsűrűség. Van sok más áramsűrűség is, és önmagában általában a villamos áramsűrűséget jelenti a szó. Ráadásul hőáramsűrűségből is van sokféle, a hőterjedés módja szerint és a fal alakja szerint.
4) Az (5.1) utáni bekezdésben megint vannak apró hibák, ihányzó szóköz és kötőjel.
5) A kapott egyenleteket nem mi tesszük egyenlővé, hanem az energimegmaradás és az állandósult állapot miatt a két réteg hőáramsűrűsége egyenlő.
6) Az (5.10)-es egyenletnél van több hiba is: az egeynletben ne legyen üres sor (76. sor), az egyenlet előtt van egy elírás, az egyenlet indokolatlanul bonyolult és az x magyarázata rossz. 0,01 méter egyenlő 10 mm-rel, ez nem leeht a 2 mm-es vízkőréteg fele.
7) A feladat végén legyen egy `\pagebreak`.

A számértékek és átalában véve a számítás menet rendben van.

**HS2**
1) Ha négyzetre emelt mértéegységek akarsz, akkor a \squared-et kell használni: `\SI{60000}{\watt\per\meter\squared}`. Ez ebben a feladatban többször előfordul.
2) Megint áramsűrűséget írtál.
3) Ennél a feladatnál meg kellene magyarázni, hogy miért a síkfalra vonatkozó egyenleteket használod, mikor a vízforraló üst valószínűleg gömb alakú!
4) Az a) rész megoldása rendben van, de a b) és a c) rész egyrész keveredik, jobb lenne szétválasztani, ugyanis megoldható a b) rész a c) eredménye nélkül.

A HS2-esből hiányzik az 25 pontos ábra.

**Comment by Szalay** [comment]
Két szintaktikai hiba van a megoldásaiban: 
![image](https://user-images.githubusercontent.com/8204804/80921773-a3af7b80-8d78-11ea-8e84-3b4b96b36569.png)

**Comment by kovacsbence3** [comment]
Javítottam a programkódon. Remélem szintaktikai hiba nem lesz benne ( a papeeria tényleg mindent lefuttat). Hozzáadtam a HS2 ábráit. A megoldásokat elválasztottam a feladat szövegtől illetve az A,B,C feladatrészt is kiemeltem. Az elírásokat, nyelvhelyességeket átnéztem, remélem nincs már több benne. Valamint átírtam, hogy a feladat szövegében csak a mennyiségek jelei legyenek, az értékek az adatok részen belül.
Kérnék egy ismételt ellenőrzést a feladatomra, illetve szeretném megkérdezni, hogy amennyiben ebben a formában adnám le a beadandót, hozzávetőlegesen hányas értékelést kapnék?
Előre is köszönöm válaszát!

**Comment by Szalay** [comment]
**HS1**
1) A feladat szövegében a falvastagságok ne d-k, hanem delták legyenek!
2) Az adatokat két sorba kellene osztani valamilyen logika mentén, hogy elférjeken.
3) Vannak ragozási hibák: T_2-vel, T_2-őt...
4) 5.8 \meter\squared
5) 5.9 Fölösleges a pont.

A megoldásod fő hibája, hogy kiszámolod a T_2-t, de az adatokban és az ábrán más a T_2, aminek emiatt rosszak az arányai. A második megadott hőmérséklet legyen T_3, mert így kell a legkevesebbet módosítani. 

**HS2**
1) A hőáramsűrűséget mindenhol 1-es indexszel írod fel, függetlenül attól, éppen melyik rétegre vonatkozik. És a hőáramsűrűségben mindegyik ű hosszú.
2) A feladat leírásban fölöslegesek a zárójelezések.
3) A T_W jelölés a wall=fal angol szóból jön, és a falhőmérsékletek többrétegű falak esetén a külső felületek hőmérsékletei. Emiatt nem jó ötlet a B) részben T_W-nek jelölni a belső réteghatár hőmérsékletét. Egyik jelölésrendszer sem tökéletes, de a legjobb megoldás általában számozni az érdekes hőmérsékleteket, és nem baj, ha feladatrészenként mást jelent ugyanaz a szám, csak le kell írni.
4) A részeket nagybetűkkel jelölted, de van ahol a szövegben kisbetűvel hivatkozol rájuk.

Az ábrák skálázását módosítani kell, hogy rendesen ki legyen töltve a hely.

**Comment by kovacsbence3** [comment]
Javítottam a hibákat és a nyelvi helyességet. a T_W -t átírtam T_3ra. Azért T_W -t használtam eredetlieg mert a példatár is ezt a jelölést használta.
A második megadott hőmérsékletet szintén T_3ra paramétereztem, ahogy tetszett javasolni.
"hőáramsűrűséget mindenhol 1-es indexszel írod fel" , én csak 1 vagy2 ilyet láttam, a legtöbb helyen rendesen 1-es és 2-es indexel van ellátva. vagy általános képlet esetén index nélkül. Ezeket átírtam, remélem erre gondolt a Tanár Úr!

Az ábrák skálázását a kétszeresére vettem, hogy jobban kitöltse a helyet.
Szeretnék még egy ellenőrzést kérni. Illetve arra szeretném megkérni a Tanár Urat, hogy egy hozzávetőleges értékelést adjon, ha ez lehetséges. Vagy legalább annyit, hogy a 100 pontból a bónusz%-al együtt megvan-e legalább a kettes!
Köszönöm válaszát!

**Comment by Szalay** [comment]
Pontoztam a jelenlegi állapotában, az eredmény 77% azaz egy kicsivel marad le a 80 %-ról. Ha szeretnél rajt javítani, akkor írok egy listát.

**Comment by kovacsbence3** [comment]
77pont a +5% nélkül? az a +5%al nincs meg pont 80.85? Vagy a 77pontban már bele van számolva a +5%? Amennyiben most nem élek a leadással és még javítok, a +5% tól elesek?

**Comment by Szalay** [comment]
Jogos az észrevétel, kimaradt a +5 százalék, javítottam a pontozást.
