### ISSUE TITLE
K1/3-as feladat ellenőrzésre feltöltve.

### ISSUE THREAD

**Issue by palkolaszlo** [PE-MK-JAKI-H/MHFGY#20]
Tisztelt Tanár úr! 

Feladatomat feltöltöttem ellenőrzésre, legyen szíves nézze át, kell-e (és ha igen mit) még változtatni rajta, hozzá adni valami. 

Előre is köszönöm! 

Palkó László
NW3WYW

**Comment by Szalay** [comment]
Megnézem a beadandót, alapvetően rendben van, a számítás menete és a számértékek is helyesek, és az ábrák is elég jók. A következő hibákat viszotn javítani kell:
1) Maradt egy Nm, ami J kellene legyen (az adatoknál).
2) Az ábrák magasságát állítnai kellene, hogy elférjen kettő egy oldalon, hogy ne maradjanak nagy üres részek. Kisebb helyeket fel lehet tölteni szöveges magyarázattal is, de ennél a feladatnál nincs miről írni fél oldalt.
3) Az első és a harmadik ábrán (p-V diagramok) csak az állapotváltozás legyen vastag, az izotermák ne!
4) A $p-V$ és a T-s$ vagy $T-S$ is egyenlet legyen, mert a diagramok megnevezése esetében is mennyiségek jeleiről van szó.
5) A diagramokon ábrázolt adat eredetéről kellene ezen felül írni néhány mondatot. Alakra jó mindegyik, de azért érdekel, hogy honann jött az adat.
6) A T-s diagramjaidnál az s-nek rossz mértékegységet adsz meg.

**Comment by palkolaszlo** [comment]
Köszönöm. 
Az ábrázolt adatok eredetéről a kódban tűntessem fel kommentben a számításhoz használt képleteket, vagy töltsem fel az excel táblát is, amiben számoltam? (esetleg mindkettő?)
