### ISSUE TITLE
latexos feladat ellenőrzése

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MHFGY#21]
Jó napot kívánok!

feltöltöttem a feladatomat , legyen szíves amint ideje engedi, ellenőrizze le nekem.

köszönöm!

**Comment by Szalay** [comment]
LaTeX-es vagy legalább latexes. És k, nem x :)

És most ellenőrzöm.

**Comment by Szalay** [comment]
A megjegyzések első része itt van: https://github.com/PE-MK-JAKI-H/MHFGY/commit/344e7d819225e13008b0a4044b61a444772a1ecc

**Comment by Szalay** [comment]
Az ábrákhoz végülis nem írtam megjegyzést, mert be kel lelőbb fejezni őket.
