### ISSUE TITLE
feladat leadása

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MHFGY#23]
Jó napot kívánok!

Feltöltöttem a feladatomat.Annyit szeretnék kérni hogy én többször is jeleztem hogy nézze át, legelőször két hete töltöttem fel a Latex-os megoldásomat, viszont én javítást nem kaptam és azért töltöttem fel ma mert szeretném azt a 10%-ot megkapni, mivel szükségem lesz rá mert az ábrával nem nagyon boldogultam. Kérem ezt vegye figyelembe, tisztában vagyok azzal hogy Önnek ez most rengeteg plusz munkát jelent főleg amilyen sokan vagyunk!Ha van még lehetőség javítani akkor szívesen élnék azzal a lehetőséggel is!
Esetleg meg tudná mondani hogy az eddigi munkám alapján legalább a kettes érdemjegy megvan, mert az nagy megkönnyebbülés lenne számomra.:)
Megértését köszönöm, és várom mielőbbi válaszát!

Tisztelettel:
Biró Géza Konrád
qiseel

**Comment by Szalay** [comment]
Az imént átnéztem a beadandód, és bár jogos, hogy kissé lemaradtam a feladatok átnézésével, de nem ezen fog múlni az eredményed. Nem pontoztam még le, de egyértelműen a kettes szint felett vagy. Az ábrákkal viszont tényleg van gond, leginkább az, hogy nem lettek befejezve.

**Comment by qiseel** [comment]
Köszönöm szépen! 
A hibákat javítottam és örömmel olvastam hogy megvan a legalább kettes:)!
