### ISSUE TITLE
Hőtan feladat leadás

### ISSUE THREAD

**Issue by rupiman97** [PE-MK-JAKI-H/MHFGY#24]
Jó napot tanár úr!

Múltkor kaptam egy pontszámot a feladatomra. Szeretném leadni a feladatomat, ehhez szükséges csinálni "pull request"-et, vagy elég az utolsó commit?

Köszönöm szépen!
Rupert Balázs

**Comment by Szalay** [comment]
Igazából készen vagy, csak a másik feladatodat is meg fogom azért nézni, bár az eredményen nem változtat. A megoldások összefésülését még nem döntöttem el, hogyan csinálom, de valószínűleg már nem lesz teendőd.

**Comment by rupiman97** [comment]
Köszönöm!
