### ISSUE TITLE
K2/3 ellenőrzésre feltöltve

### ISSUE THREAD

**Issue by galvince98** [PE-MK-JAKI-H/MHFGY#25]
Tisztelt tanár úr!

Felöltöttem a feladatunkat (X3CGOS és PU7YJ4) ellenőrzésre, ha ideje engedi kérem ellenőrizze le.
Köszönöm!

**Comment by Szalay** [comment]
Átnézte, néhány megjegyzést a forrás mellés írtam (https://github.com/PE-MK-JAKI-H/MHFGY/commit/90678c3429b8abcba35dd90db4e5693a3f11e737), hogy könnyebb legyen beazonosítsni, mire vonatkozik, az általánosabb észrevételek pedig a következők:
1) A hőmérsékletek nagy T-vel, a nyomások kis p-vel legyenek jelölve.
2) A tömegfajlagos munka jele kis w. Több helyen hibásan nagy W szerepel.
3) Sok helyen dupla nyilat írtatok egyszerű egyenlőségjel helyett. A dupla nyíl egyirányú logikai következményt jelent, nem egyenlőséget vagy mértékegység-átváltást. Ha végeredményeket ki akarjátok emelni, akkor dupla aláhúzást használjatok!
4) Itt-ott mondatvégi pont és irásjel (vessző, felkiáltójel) utáni szóköz lemaradt.

A gyakori apróbb hibákat a Moodle-beli leírás alján kigyűjtöttem. Ezeket magatok is le tudjátok ellenőrizni.

A beadandó egyetlen súlyosabb hibáját a T-s diagramokon a megtört izobár vonalak jelentik. Ezeket ki kell javítani.

**Comment by galvince98** [comment]
A hibákat kijavítottuk és feltöltöttem a javított verziót, kérem majd nézze át.
Köszönöm!

**Comment by Szalay** [comment]
Pontoztam a jelenlegi állapota alapján. Az értékelést megtaláljátok a Google-táblázatban. A héten még járt érte +5 %. Az ötös határ 80 %, ha szeretnétek javítani, akkor írok egy listát a hibákról és a hiányosságokról.

**Comment by galvince98** [comment]
Köszönjük, maradnánk a mostani eredménynél. Azt szeretném megkérdezni ,hogy a végleges beadáshoz van valami útmutató a moodle-be vagy bárhol máshol?

**Comment by Szalay** [comment]
Részetekről a végleges beadás nem igényel már semmit, én viszont bejelölöm a cellákat a Google-táblázatban zölddel :)
