### ISSUE TITLE
K1/3 feladat (javítva) ellenőrzésre feltöltve

### ISSUE THREAD

**Issue by palkolaszlo** [PE-MK-JAKI-H/MHFGY#26]
Tisztelt Tanár úr! 

A korábbi hibákat javítva feltöltöttem a feladatot ellenőrzésre, ha minden megfelelő, kell még tennem valamit a Githubon, hogy végleges legyen?

Üdvözlettel: Palkó László

**Comment by Szalay** [comment]
Megnéztem, az értékelést megtalálod a Google-táblázatban.
