### ISSUE TITLE
2/MH14. és MH15.

### ISSUE THREAD

**Issue by smisia** [PE-MK-JAKI-H/MHFGY#27]
Tisztelt Tanár Úr!

Amennyiben lehetséges, esetleg le tudná ellenőrizni az eddig megoldott és felírt feladataimat? (a T - s diagram még hiányzik)

Válaszát előre is köszönöm!
Somodi Mihály (RXEZFF)

**Comment by Szalay** [comment]
A számítások menete és a számértékek is rendben vannak. Apróbb hibákat látok csak, pl. 2.14/15-höz: a tömegfajlagos munkákat kis w-vel szokás jelölni, hasonlóan a többi tömegfajlagos mennyiséghez.
