### ISSUE TITLE
hőszivattyús feladat

### ISSUE THREAD

**Issue by tzoltan56** [PE-MK-JAKI-H/MHFGY#28]
Tisztelt Tanár úr!
Olyan problémám lenne,hogy kevésnek tűnik a feladatom által megadott adat (az előadásból kiindulva vetődött fel bennem a gyanú,mert ott több adatal dolgozott a tanár úr), szeretnék ez ügyben tanácsot/segítséget kérni
Válaszát előre is köszönöm!
A feladatom szövege: ( 69. oldal , 3. feladat)
Mekkora fűtőteljesítményt szolgáltat egy olyan Carnot-körfolyamat szerint müködő hőszivattyú, amelynek teljesítmény-szükséglete 50 kW, továbbá + 5 °C és + 27 °C határok között dolgozik? Abrázolja a körfolyamatot T-s diagramban és jelölje meg rajta a fűtésre használható hőt!

**Comment by Szalay** [comment]
A kulcsszó a Carnot-körfolyamat. Ez azt jelenti, hogy a T-s diagramban a körfolyamat téglalap alakú, azaz vagy nem vízről van szó, vagy legalábbis nem a Rankine--Clausiushoz hasonló vízgőz körfolyamatról. Pusztán a hőmérséklet-értékek alapján ki tudod számolni a fajlagos hűtőteljesítményt és abból a hőáramot.

**Comment by Szalay** [comment]
Leellenőriztem közben a feladatot, illetve a feladatválasztásod. A számítás elvégzése után is él az előző megjegyzésem. A feladatválasztásodnál viszont volt egy probléma, a K2/3-as 75 pontos, az MH3 pedig 10 volt, azaz csak 85 pontnyi feladatot választottál. Emiatt az MH3-at kiegészítettem egy 15 pontos résszel.
