### ISSUE TITLE
K2/1 feladat feltöltve ellenőrzésre

### ISSUE THREAD

**Issue by feherarpad3** [PE-MK-JAKI-H/MHFGY#30]
Tisztelt Tanár úr!

A hét elején feltöltöttem a feladatomat ellenőrzésre, ha az ideje engedi kérem ellenőrizze le, ha jó akkor elindítom a pull requestet. 

Üdvözlettel: Fehér Árpád (VX12Z6)

**Comment by Szalay** [comment]
Átnéztem, néhány apróbb dolgot kellene javítani:
1) Az a) rész elírásában a p = áll legyen egyenletben, de úgy, hogy az állandó legyen kiírva, és az egyenleten belül szövegként hozd létre
2) A T-s diagramon ne maradjon rajt a rács, telejsen el lehet rejteni.
3) A T-s diagramon túllóghatna az izobár vonal kicsit a 4-es ponton, illetve mellé kellene írni, hogy mekkora nyomáshoz tartozik.
4) Az egyenletek előtt lehetne egy kicsit részletesebb magyarázat.

A fentieket leszámítva rendben van a feladat.

**Comment by feherarpad3** [comment]
Köszönöm!

**Comment by feherarpad3** [comment]
Feltöltöttem a végleges verziót.

**Comment by Szalay** [comment]
Pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban. Ha még javítanál rajt, akkor a T_köz kerüljön fel a T-s diagramra, a d a teljes differenciálokban \dif legyen, és
4) Az egyenletek előtt lehetne egy kicsit részletesebb magyarázat.

**Comment by feherarpad3** [comment]
Megnéztem a pontozást, ha lehetséges én már ezen javítani nem szeretnék. A jelenlegi pontot és az azzal járó jegyet elfogadom.
