### ISSUE TITLE
K1/7. feladat és K6/3. feladat ellenőrzés

### ISSUE THREAD

**Issue by liongon97** [PE-MK-JAKI-H/MHFGY#33]
Tisztelt Tanár Úr!
Kérem ellenőrizze le a leadott fájlokat. (Fontos, K1/7.-es feladatnál a T-s diagramhoz egy 
külső txt fájlból nyeri ki az adatokat a fájl.) Köszönöm szépen!

**Comment by Szalay** [comment]
A fájlok elrendezését és a sablon működését nem sikerült tökéletesen megérteni. A saját fájljaidban csak a `\section*`-nál kezdődő saját megoldásodnak kell benne lenni.

Az MHFGY.tex a gyökérdokumentum. Ebben benne van az elején a Jaki fájlok behúzása, aztán a címoldal, a tartalomjegyzék, és a fejezetekre bontás.

A saját fájljaid szöveges tartalmát az `\input` gyakorlatilag bemásolja az MHFGY.tex-be a fordítás során, ezért a saját fájljaidban nem kell újra mindent beállítani.

A saját fájljaid elejét, és a legvégükről a fölösleges `\end{document}`-et töröld ki.

![image](https://user-images.githubusercontent.com/8204804/81916926-cd686e00-95d4-11ea-9408-30112a720d9f.png)

**Comment by Szalay** [comment]
A `tv3aa4_k17.tex` és `tv3aa4_k63.tex` önmagában nem fordítható, és ez így jó. Az gyökérdokumentumot kell lefordítani, és a két feladatodnak oda kell beépülni.

**Comment by Szalay** [comment]
A feladatok megoldására is ránéztem, a következőket vettem észre:

**1/7**
1) Keveredbek az áallpotjelzők összeadódó és tömegfajlagos változatai.
2) Vannak fölösleges pontok az egyenletekben.
3) A szövegben megjelenő betűjelek mindig legyenek sorközi egyenletben (`$q$`)!
4) A telejs differenciál operátor álló d betű, és a `\dif` paranccsal szedhető.

A számítás menete és az eredmények rendben vannak.

**1/9**
1) A $Re$ és a $Nu$ a szövegben is legyen egyenlet, és ezeket jelzőszámoknak szokták hívni magyarul.
2) Egy pár mondatos magyarázat kellene még a feladathoz.
3) Hausen vagy Hausensen?

Itt az eredményeket nem ellenőriztem, mert még nem oldottam meg a feladatot, de nagyságrendileg jónak tűnnek.

**Comment by Szalay** [comment]
A két feladat csak 75 pont, kereshetsz még egy 25 pontos részt, vagy valamelyiket ki is lehet bővíteni.
