### ISSUE TITLE
Gőztároló MHFGY 3/4

### ISSUE THREAD

**Issue by szucsnorbert177** [PE-MK-JAKI-H/MHFGY#34]
Tisztelt Tanár Úr! Lenne szíves a feladatomban egy kis útmutatást nyújtani? Nem tudom egyedül megoldani. Előre is köszönöm! (3. rész 4. feladata az enyém)
Tisztelettel: Szücs Norbert W53AAJ

**Comment by Szalay** [comment]
Erre ha minden igaz válaszoltam levélben.
