### ISSUE TITLE
K5/3 feladat ellenőrzése

### ISSUE THREAD

**Issue by SteiberArpad** [PE-MK-JAKI-H/MHFGY#35]
Tisztelt Tanár Úr!

Kérem ellenőrizze le az MH31 és K5/3 feladatok megoldásait!

**Comment by Szalay** [comment]
A Google-táblázat szerint az MH31-et, a HS3-at és az MH21-et választottad, ami több, mint 100 pont, ráadásul a K5/3 valaki másé.

**Comment by Szalay** [comment]
A feltöltött anyagban a K4/1-es feladat szövegével egy másik feladat megoldáva van benne.

**Comment by SteiberArpad** [comment]
Ha jól értem akkor a feladat számozásával van probléma, MH-val kellett volna jelölnöm, a megoldott feladataim a "Háromrétegű síkfal hőforgalma és hőmérsékletei(HS3)" és a "Fojtószelepes ammónia hűtőgép(MH31)"

**Comment by SteiberArpad** [comment]
Az MH21-es feladatot nem oldottam meg.

**Comment by Szalay** [comment]
Tisztul a kép :) 
1) Az MH21-től akkor töröld a Neptun-kódod.
2) A megoldások fájljai megvannak, de a gyökérdokumentumból hiányzik az egyik inputja, a másik pedig félig a 4/1-es.

**Comment by SteiberArpad** [comment]
A 4/1 ből szedtem ki a görbét.

**Comment by SteiberArpad** [comment]
Módosítottam a gyökérdokumentumba történő beszúrásokat. 
Az MH31 a 
![image](https://user-images.githubusercontent.com/63042279/82207326-ef7e2b00-9909-11ea-877b-524d75689fc8.png)
![image](https://user-images.githubusercontent.com/63042279/82207350-fd33b080-9909-11ea-9dee-4d77d45e8e26.png)

**Comment by Szalay** [comment]
Látom, közben frissítetted. Most jónak néz ki, le fogom ellenőrizni.

**Comment by Szalay** [comment]
Az MH31-es feladat rossz. Mármint a feladatgyűjteményben rossz, mert hibás adatokat adtak meg. Ezt javítani fogom, és megkapod a helyes adatokat. A megoldásod egyébként ettől függetlenül tartalmazott egy elvi hibát, de erre majd visszatérek, mikor megcsináltam a helyes adatokat (még ma, ha minden jól megy).

**HS3**
Ez a feladat alapvetően rendben van, néhány kisebb javítanivalót találtam csak: https://github.com/PE-MK-JAKI-H/MHFGY/commit/7ebad0d61a48111a9a2822428ada9de063dd1e6e

**Comment by Szalay** [comment]
Átnéztem az MH31-et, előszöris itt vannak a helyes adatok, kiegészítve a feladat által nem megadott nyomásokkal: 
![image](https://user-images.githubusercontent.com/8204804/82246250-9aabd600-9944-11ea-8ee8-59ca1ee7b4bb.png)

**Comment by Szalay** [comment]
A feladat szövegében szerepel egy fontos kifejezés: **a kompresszor telített gőzt szív be**. Ez azt jelenti, hogy az 1-es pont az x=1-es fázishatáron van. A körfolyamatnak így kelle kinéznie:
![image](https://user-images.githubusercontent.com/8204804/82246429-f2e2d800-9944-11ea-8d58-245faaba0cc6.png)

**Comment by Szalay** [comment]
A kompresszor utáni pont hőmérséklete és hőtartalma: 
![image](https://user-images.githubusercontent.com/8204804/82247085-1b1f0680-9946-11ea-9cce-8e5d848c8169.png)

**Comment by Szalay** [comment]
A h_2 izentalpikus vonal adatsora:
s T
7.389 72.681
7.185 73.292
6.983 74.515
6.785 76.960
6.588 80.017
6.391 84.296
6.198 90.410
6.009 98.968
5.830 111.195
5.658 127.089

**Comment by Szalay** [comment]
A h_3 izentalpikus vonal (tiszta fojtás) adatsora: 
s T
1.879 24.901
1.882 20.000
1.885 15.000
1.889 10.000
1.895 5.000
1.902 0.000
1.912 -5.000
1.923 -10.000
1.936 -15.000

**Comment by SteiberArpad** [comment]
Szükségem lenne 2.36bar-nál a T-s diagram adataira. 
Megróbáltam a wolframnotebookból előszedni, de amikor copy to clipboardot nyomok ezt másolja:

InterpretationBox["\"\:f7c1\:f7c9\:f7c8RowBox[{\"\\:f3b5p = \", StyleBox[TemplateBox[{\"1\", \"\\\"bar\\\"\", \"bar\", \"\\\"Bars\\\"\"}, \"Quantity\", SyntaxForm -> Mod], ShowStringCharacters -> False], \"\", \",\", \" \", StyleBox[RowBox[{\"16\"}], ShowStringCharacters -> False], \" pont\\:f3b5\"}]\:f7c0\"", StringForm["p = ``, `` pont", Quantity[1, "Bars"], 16], Editable -> False]

**Comment by Szalay** [comment]
s T
0.013 0.850
0.426 29.250
0.802 57.650
1.147 86.050
1.468 114.450
1.587 125.523
7.072 125.523
7.163 142.850
7.301 171.250
7.427 199.650
7.545 228.050
7.657 256.450
7.762 284.850
7.863 313.250
7.960 341.650
8.052 370.050
8.142 398.450
8.228 426.850
