### ISSUE TITLE
Vízgőz állapotváltozások ábrai kész

### ISSUE THREAD

**Issue by LokosGabor** [PE-MK-JAKI-H/MHFGY#36]
Tisztelt Tanár Úr!
Készítettem egy commitot és feltöltöttem ide a vízgőz állapotváltozások ábráiról. Szeretném megkérdezni hogy az ábrák adatok, stílus, és vonalak szempontjából megfelelőek-e? Természetesen ez még csak egy nyers verzió. És már készül az ábrák mellé a rövid szöveges magyarázat képletekkel kiegészítve.
Válaszát előre is köszönöm!

**Comment by LokosGabor** [comment]
Tisztelt Tanár Úr!
Közben elkészült a végleges verzió is. Erről is készítettünk egy commitot és feltöltöttük.
Szeretnénk megkérdezni hogy ez a verzió jó-e így vagy kell még rajta valamit kiegészíteni.
Válaszát előre is köszönöm!

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtaláljátok a Google-táblázatban.

Nem tökéletes, de mivel a jegyen nem változtat, ezért nem javíttatom ki a hibákat.
