### ISSUE TITLE
K1/7. és K6/3. feladat második ellenőrzése

### ISSUE THREAD

**Issue by liongon97** [PE-MK-JAKI-H/MHFGY#37]
Tisztelt Tanár Úr! 

Javítottam a dokumentumokat. Kérem ellenőrizze le, hogy most már kielégítő-e a feladatok megoldásai. Ha kielégítőek a megoldások, akkor a mostani verzió a végső verzió és beadnám a feladatok megoldásait. Köszönöm szépen!

**Comment by Szalay** [comment]
Pontoztam a beadandód a jelenlegi állapota alapján, a pontozást megtalálod a Google-táblázatban. Ha javítanál az eredményen, akkor írok egy listát.

**Comment by liongon97** [comment]
Tisztelt Tanár Úr!
Szeretnék javítani rajta, amivel megvan a 3-as jegy.

**Comment by Szalay** [comment]
Rejtsd el a rácsot a T-s diagramon, és javítsd ezeket: https://github.com/PE-MK-JAKI-H/MHFGY/commit/e0e9621df6c37843e5a309569ba9691256e56133

Máshogy voltak még a fájljaid, de így egy helyen tudtam megjelölni a javítandó dolgokat.
