### ISSUE TITLE
K 1/4 -és feladat pontozása

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MHFGY#40]
Jó napot kívánok !

Legyen szíves pontozza le a feladatomat amint ideje engedi , én már indítottam kb 10-12 napja egy pull requestet. 

Köszönöm !

Bíró Géza 
qiseel

**Comment by Szalay** [comment]
A pull request nem kellett volna, ezt az issue-t kellett volna előbb megnyitni, mert az issue-kon megyek végig ellenőrzésnél. 

Ettől függetlenül most megnéztem a feladatot és hát za ábrák gyakorlatilag hiányoznak. Lepontoztam, de még nem üti meg a kettes szintet.

Legalább az ábrákat pótolni kell, de szövegben is vanank hibák.

**Comment by qiseel** [comment]
Tisztelt Tanár Úr ! 

Én már kezdek kikészülni , két hete ezt tetszett nekem írni erre a feladatra  “Az imént átnéztem a beadandód, és bár jogos, hogy kissé lemaradtam a feladatok átnézésével, de nem ezen fog múlni az eredményed. Nem pontoztam még le, de egyértelműen a kettes szint felett vagy. Az ábrákkal viszont tényleg van gond, leginkább az, hogy nem lettek befejezve.“

Idézem “egyértelműen a kettes szint felett vagy “ most meg azt tetszik írni hogy nem , mi változott azalatt a két hét alatt ?!

**Comment by Szalay** [comment]
Az változott, hogy most nem csak a beadandó alapján írok véleményt, hanem szigorúan összevetem a feladatkiírással, és az elkészített anyag alapján adok pontot, hanem a feladatkiírást követve pontozok. Voltak, akik egész feladatrészeket kihagytakm és igazából ez történt nálad is. De részletezem:

Így néz ki a feladat:
![image](https://user-images.githubusercontent.com/8204804/82308454-1a2bba80-99c2-11ea-857d-d3d68b145c33.png)

A felső sorban az 5/5 20/20 25/25-ből a két utolsó 25-ös az ábrára jár. Ezen felül még 25 pont jár az ábrára, mert babrálni kell vele. Ez ugye azt jelenti, hogy a 100-ból 75 pont az ábrázolás, amit nagyrészt nem csináltál meg.

A múltkor feltételezem megnéztem a beadandót, a leírás és megoldás menete rendben volt, a dokumentum rendezett, és nem néztem meg, hogy milyen pontozást társítottam a feladathoz. A következőt tudom javasolni: mivel rám kellett várnod elég sokáig, és én írtam helytelen értékelést, a +10 %-kot megadom, viszont leglább az egyik ábrát el kellene készíteni.

**Comment by qiseel** [comment]
Az iPhone-omról küldve

2020. máj. 19. dátummal, 11:23 időpontban Szalay <notifications@github.com> írta:

﻿

Az változott, hogy most nem csak a beadandó alapján írok véleményt, hanem szigorúan összevetem a feladatkiírással, és az elkészített anyag alapján adok pontot, hanem a feladatkiírást követve pontozok. Voltak, akik egész feladatrészeket kihagytakm és igazából ez történt nálad is. De részletezem:

Így néz ki a feladat:
[image]<https://user-images.githubusercontent.com/8204804/82308454-1a2bba80-99c2-11ea-857d-d3d68b145c33.png>

A felső sorban az 5/5 20/20 25/25-ből a két utolsó 25-ös az ábrára jár. Ezen felül még 25 pont jár az ábrára, mert babrálni kell vele. Ez ugye azt jelenti, hogy a 100-ból 75 pont az ábrázolás, amit nagyrészt nem csináltál meg.

A múltkor feltételezem megnéztem a beadandót, a leírás és megoldás menete rendben volt, a dokumentum rendezett, és nem néztem meg, hogy milyen pontozást társítottam a feladathoz. A következőt tudom javasolni: mivel rám kellett várnod elég sokáig, és én írtam helytelen értékelést, a +10 %-kot megadom, viszont leglább az egyik ábrát el kellene készíteni.

**Comment by qiseel** [comment]
Tisztelt Tanár Úr!

Nagyon szépen köszönöm, megcsinálom mindenképp viszont 1-2 nap haladékot nem lehetne kérni mert én tényleg abban a tudatban voltam hogy megvan a min kettes és azért is csináltam meg a határidő előtt korábban mert ezen a héten pénteken vizsgázom.Ha nem akkor péntekig feltöltöm

Várom mielőbbi válaszát!

Biró Géza

**Comment by Szalay** [comment]
Indolkolt esetben a határidőt rugalmasan értelmezem, és ez most egy indokolt eset.

**Comment by qiseel** [comment]
Rendben és köszönöm ! Még egy kérdés , nem kaphatnék plusz egy másik feladatot mert nagyon szeretném teljesíteni a tárgyat mert így 33 évesen nagyon nem szeretnék csúszni és próbálom megcsinálni ezt az ábrát de sehogy sem megy ......!

**Comment by qiseel** [comment]
Köszönöm ! Héten vasárnapig megpróbálom feltölteni !

**Comment by qiseel** [comment]
Jó napot kívánok !

Ebben az esetben a rugalmas határidő mit jelent ? Csak szeretném tudni konkrétan mi a legvégső időpont ?

Válaszát előre is köszönöm !

**Comment by Szalay** [comment]
A vizsgaidőszak másopdik hetének vége, ami a gyakorlatban a harmadik hét hétfő.
