### ISSUE TITLE
2/MH15. T-s diagram

### ISSUE THREAD

**Issue by smisia** [PE-MK-JAKI-H/MHFGY#41]
Tisztelt Tanár Úr!

Ha ideje engedi legyen szíves ellenőrizni az MH15-ös feladatban elkészített T-s diagramomat.

Tisztelettel,
Somodi Mihály

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

Nem tökéletes, de mivel a jegyen nem változtat, ezért nem javíttatom ki a hibákat.
