### ISSUE TITLE
Feladat javításra kész (FWHG4S)

### ISSUE THREAD

**Issue by dervakrisztian** [PE-MK-JAKI-H/MHFGY#42]
Tisztelt Tanár Úr!

Elkészültem a beadandómmal (K7/7-es feladat).
Kérem szíveskedjék leellenőrizni.

Dervalics Krisztián (FWHG4S)
Gépészmérnök alapszakos hallgató

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítni a beadandón, akkor írok egy listát a hibákról.

**Comment by dervakrisztian** [comment]
Köszönöm a javítási lehetőséget, de idő hiányában nem élnék vele.

**Comment by Szalay** [comment]
Rendben, rögzítettem.
