### ISSUE TITLE
Kész Feladat leadása QWP76T

### ISSUE THREAD

**Issue by rezibence** [PE-MK-JAKI-H/MHFGY#45]
Tistelt Tanár Úr!
Kész hőtan feladatomat szeretném leadni (QWP76T az M20 as feladatot).
Tisztelettel és Köszönettel: Rezi Bence gépészmérnöki alapszak.

**Comment by Szalay** [comment]
A megoldásnak nem csak annyiból kellene állni, hogy leírod az egyenletet, hanem egy minimális magyarázat kellene mindegyik lépéshez. 

1) A tömegfajlagos hőtartalmat h-val jelöld! 
2) A tömegfajlagos munkák jele ki w legyen!
3) 4 különböző mennyiséget jelölsz i-vel. Valahogy meg kellene különböztetni őket.
4) A T-s diagram nem hibás, de a szivattyú munkája nincs rajt. 

Néhány további megjegyzést a forrás mellé írtam: https://github.com/PE-MK-JAKI-H/MHFGY/commit/c0b26dacc9d45def0d5ad3d22dc3ac4ac7e1e793

**Comment by rezibence** [comment]
Köszönöm szépen kijavítom!

**Comment by rezibence** [comment]
Tisztelt Tanár Úr!
KIjavítottam amiket tetszett jelezni remélem, hogy igy már elfogadható lesz.
Köszönöm szépen a segítséget!
Tisztelettel és Köszönettel Rezi Bence

**Comment by Szalay** [comment]
A feladatzlistában be vagy írva a 6/1-es kétfős feladathoz, de onnan törölhetnéd magad, mivel nem azt a feladatot csinálod,

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban. És a másik feladattól ne felejtsd el törölni magad!

**Comment by rezibence** [comment]
Tisztelet Tanár Úr!
Köszönöm szépen a javítást és a segítséget. A 6/1 es kettős feladattól töröltem magam bennfelejtettem magam korábban elnézést kérek ezért.
Tisztelettel és Köszönettel: Rezi Bence
