### ISSUE TITLE
feladat ellenőrzés (4/3) + felmerült kérdés (MH3)

### ISSUE THREAD

**Issue by tzoltan56** [PE-MK-JAKI-H/MHFGY#46]
Tisztelt Tanár Úr!
Szeretném kérni a feladatom ellenőrzését.Valamint olyan kérdésem lenne az MH3 feladattal kapcsolatba, hogy miként tudnék Carnot-körfolyamatot ábrrázolni hőmérséklet és entrópia értékek ismerete hiányában?
[Beadando_hotan.pdf](https://github.com/PE-MK-JAKI-H/MHFGY/files/4645482/Beadando_hotan.pdf)
(D0EAD9)

**Comment by Szalay** [comment]
**4/3**
Az összefüggések jók, de
1) A fajlagos fűtőteljesítmény hibás, mert Celsiusban számolsz, mikor kelvinben kellene. Nem mindegy, hogy hőmérséklet, vagy hőmérsékletkülönbség.
2) Az előbbi miatt rossz után a fűtésre használható hőáram.
3) A lépésekhez kellene írni néhány magyarázó mondatot, melyik mennyiség micsoda.

A feladat a hőmérsékleteket megadja, az entrópia abszolútértéke pedig végülis nem számít, úgyhogy megválaszthatod úgy a két értéket, hogy jól nézzen ki az ábra, csak ne írj értékeket a tengelyre.

**MH3**
Ez rendben van, de néhány magyarázó mondat ide is kell.

**Comment by tzoltan56** [comment]
Az MH3 -nál viszont nem ad meg a feladat hőmérséklet illetve entrópia értékeket,a kérdésem arra feladatra irányult az ábrázolással kapcsolatban.

**Comment by tzoltan56** [comment]
a fájlt kódját txt fájlba töltöm fel, mert így talán gyorsabb. A kód kezdetleges és főleg tesztelés szándékából íródott így.
[MFHGY_MH3.txt](https://github.com/PE-MK-JAKI-H/MHFGY/files/4647159/MFHGY_MH3.txt)
(nem leforduló SI mértékegységek)

**Comment by Szalay** [comment]
A kiadott sablon 3 fájlból épül fel: a gyökérdokumentum, a JakiAlap.tex és a JakiTikz.tex. A két utóbbi tartalmazza a csomagok betöltését és beállítását. A \SI parancs az siunitx csomagból jön.

Ha akarsz egy minimális gyorsuan forduló változatot, akkor ezt csináld:
`
% A dokumentum kezdete
\documentclass[11pt, a4paper]{report}

% Ide kell a két sablon fájl
\input{./JAKI/JakiAlap.tex}
\input{./JAKI/JAkiTikz.tex}

% A dokumentum tartalmának kezdete
\begin{document} 

\section*{MH3. feladat}
\addcontentsline{toc}{section}{K5/1. feladat: Hőterjedés sík kazánfalban}
\begin{tabular}{ | p{2cm} | p{14cm} | } 
	\hline
	Szerző & Török Zoltán D0EAD9 \\ 
	\hline
	Szak & Gépészmérnök alapszak\\ 
	\hline
	Félév & 2019/2020 II. (tavaszi) félév \\ 
	\hline
\end{tabular}
\vspace{0.5cm}

% A feladat szövege
\noindent Mennyi munkát kaphatunk abból a körfolyamatból, amelynek a termikus hatásfoka  $\eta_T=0,37$ és az elvezetett hőmennyiség $\SI{45}{\kilo\joule}$?         ($W_{kinyert}=\SI{26,43\cdot10^3}{\joule}$ )


% Oldaltörés
\pagebreak
% A dokumentum tartalmának vége
\end{document
`

**Comment by tzoltan56** [comment]
Tisztelt Tanár úr!
A probléma nem oldódott meg!
