### ISSUE TITLE
Feladat 2/4

### ISSUE THREAD

**Issue by zobokip** [PE-MK-JAKI-H/MHFGY#47]
Tisztelt Tanár Úr! 

Feltöltöttem a feladat-megoldásomat ellenőrzésre. Kérem ha ideje engedi nézzen rá.

Köszönettel: Zoboki Péter

**Comment by Szalay** [comment]
Nem látok C0KH0R ágat. Hova töltötted fel?

**Comment by zobokip** [comment]
Nem volt branchem ezen az ágon, mert az MHEK-ba csináltam. Ellenben, most hogy készítettem egy újat felajánlotta, hogy az eddigi változtatásaimat áthozhatom, mire kitörölte az egész eddigi mappát. Van valami ötlete, hogyan tudnám visszahozni?

**Comment by zobokip** [comment]
Tisztelt Tanár Úr! 

Ha minden igaz, akkor ismét elküldtem Önnek. Kérem tekintse meg.

**Comment by Szalay** [comment]
Átnéztem és pontoztam is. Lenne benen mit javítani, de mivel a jegyen nem változtatna, ezért nem kérem. Az eredményt megtalálod a Google-táblázatban.
