### ISSUE TITLE
Gáz térfogatárama MHFGY 1/1

### ISSUE THREAD

**Issue by Kislovag** [PE-MK-JAKI-H/MHFGY#48]
Tisztelt Tanár Úr!

Az címben említett feladat (Gáz térfogatárama MHFGY 1/1) elkészítése közben találkoztam azzal a problémával, hogy a számolásaim alapján nem jön ki az előre megadott érték. Azonban amennyiben a gáz térfogat változására számított munkát elhanyagolom, úgy eléggé közeli értéket kapok a megadott megoldáshoz. Az a kérdésem lenne ezzel kapcsolatban, hogy a megoldásmenetem nem jó vagy esetleg tényleg el kell hagyni a térfogat változásra fordítódó munkát? A megoldásmenetem képen mellékeltem. Válaszát előre is köszönöm.

Tisztelettel,
Kocsor Péter Ernő
B00RZ7 

![MHFGY_1_1](https://user-images.githubusercontent.com/63042401/82306882-ec457680-99bf-11ea-9360-cabb4547ac50.jpg)

**Comment by Szalay** [comment]
1) A feladatgyűjteményben megadott számérték jó, viszont a QD az \diameter D akart lenni, és aki beírta, az nem csak ezt nem tudta, hanem azt sem, hogy az átmérőjelet rajzon muszáj, a szövegben nem szabad kitenni.
2) A feladat w-vel jelöli az áramlási sebességet, de ne tévesztd össze a tömegfajlagos munkával! Ebben az esetben igazából nincs jó betű, a sebesség lehetne c, v, u, de mindegyik foglalt a hőtanban.

A megoldásod a sűrűségek számításáig jó, utána viszont az levegő szállításos hőáramának növekedését kellene kiszámolni.

**Comment by Kislovag** [comment]
Köszönöm szépen a válaszát. Továbbá az a kérdésem nem tisztázódott még, hogy a térfogat tágulásáért végzett munkával kell-e számolnom? Illetve amennyiben figyelembe veszem a levegő tágulását, úgy a térfogatáramot (amely menet közben növekszik) a melegítés utáni vagy előtti állapotban adjam meg?
Illetve, csak a biztosság kedvéért, mivel a QD a fűtőtest átmérője, így hosszúsági adat hiányában vehetem a fűtőtestet felületszerűnek ?

**Comment by Szalay** [comment]
1) Csak a szállításos hőáram (=a hőmérséklet) változásával kell számolni.
2) Mivel változik, ne térfogatáramban, hanem tömegáramban gondolkodj!
3) A QD csak D, és a cső belső átmérője.

**Comment by Kislovag** [comment]
Ismét köszönöm a válaszát. Az eddigiek alapján a képen mellékelt megoldásokra jutottam. Az utolsó kérdésem az lenne, hogy jók-e az eredmények, így hogy (reményeim szerint) csupán kerekítési eltérésekkel terheltek?
![MHFGY_1_1_b](https://user-images.githubusercontent.com/63042401/82335346-7e15a980-99e9-11ea-96bb-da9102fc8fab.jpg)

**Comment by Szalay** [comment]
Csak kerekítési hibát látok, azt sem a te megoldásoban, hanem a feladatgyűjteményben.

**Comment by Szalay** [comment]
A térfogatáram is rendben van.

**Comment by Szalay** [comment]
Közben azt is leellenőriztem, amit feltöltöttél. Az eredményt megtalálod a Google-táblázatban.

Az MH25 kicsit hiányos, de 100-ból így is sikerült elég sok pontot összehozni. Mivel a hőtan szempontjából gyakorlatilag vége a félévnek, elfogadom így a megoldásaid, ahogy vannak.
