### ISSUE TITLE
K1/7. és K6/3. feladat hibajavításai (e0e9621)

### ISSUE THREAD

**Issue by liongon97** [PE-MK-JAKI-H/MHFGY#49]
Tisztelt Tanár Úr!

Javítottam a e0e9621 felsorolásban található hibákat. Ha kielégítő a feladatmegoldás, akkor ezek a fájlok a végső megoldás.

Tisztelettel, Hadabás Márk István (TV3AA4)

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
