### ISSUE TITLE
Hőtan K1/4

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MHFGY#5]
![Hőtan K14](https://user-images.githubusercontent.com/63043062/79096776-541ff600-7d5e-11ea-9232-32b36e10a94e.jpg)

**Comment by qiseel** [comment]
Ehhez a feladathoz kell valamilyen magyarázatot/megjegyzést írni?

**Comment by Szalay** [comment]
A főbb lépésekhez egy-egy félmondat elég. De ezen felül az eredmények közötti eltérést és a negatív előjeleket is meg kellene magyarázni.
