### ISSUE TITLE
Gőztároló MHFGY 3/4.

### ISSUE THREAD

**Issue by szucsnorbert177** [PE-MK-JAKI-H/MHFGY#51]
Tisztelt Tanár Úr! Lenne szíves megnézni a feladat megoldási próbálkozásomat? Válaszát előre is köszönöm!  Tisztelettel: Szücs Norbert W53AAJ
![hőtan](https://user-images.githubusercontent.com/63372246/82325744-03925d00-99dc-11ea-9999-bca838959db9.jpg)
![hőtan2](https://user-images.githubusercontent.com/63372246/82325746-042af380-99dc-11ea-9341-2d45010cd6cb.jpg)

**Comment by Szalay** [comment]
Erre már válaszoltam levélben.

**Comment by Szalay** [comment]
Jelentleztél a csütörtöki szóbelire. Ez azt jelenti, hogy mégsem csinálod meg a beadandót?
