### ISSUE TITLE
HS3 és MH31 feladatok ellenőrzése

### ISSUE THREAD

**Issue by SteiberArpad** [PE-MK-JAKI-H/MHFGY#52]
A HS3 és MH31 feladatokban elvégeztem a javításokat, legyen szíves leellenőrizni a feladatokat.

**Comment by Szalay** [comment]
Nem kell pull request, elég, hogy nyitottál egy Issuet.

Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
