### ISSUE TITLE
K1/2 és MH8 feladatok kész

### ISSUE THREAD

**Issue by KustanGergely** [PE-MK-JAKI-H/MHFGY#54]

**Comment by Szalay** [comment]
Van egy szintaktikai hiba: 
![image](https://user-images.githubusercontent.com/8204804/82836269-89c00f00-9ec6-11ea-9d64-905ef8eecefa.png)

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban. Ez akkor lesz érvényes, ha a fenti szintaktikai hibát javítod.
