### ISSUE TITLE
K1/8. és az MH9. feladat

### ISSUE THREAD

**Issue by SzauerJanos** [PE-MK-JAKI-H/MHFGY#55]
Tisztelt Tanár Úr!
Elkészült a végleges verzió. Kérem nézze meg a feladatokat.

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban. Ha javítanál a négyesért, akkor az MH9-est kellene kiegészíteni azzal, hogy milyen módon határoztad meg a gőztáblázati adatokat.

**Comment by SzauerJanos** [comment]
Javítottam a feladatot.
