### ISSUE TITLE
MH28 feladat

### ISSUE THREAD

**Issue by Batorrrrr** [PE-MK-JAKI-H/MHFGY#56]
Tisztelt Tanár Úr!

Szeretnék kérni egy ellenőrzést az MH28-as feladatra.

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítni a beadandón, akkor írok egy listát a hiányosságokról.

**Comment by Szalay** [comment]
Utólag leellenőriztem a feladatválasztást is ,hogy azt oldottad-e meg, amit kiválasztottál, és azt telejsen megoldottad-e (mert volt már, akinek ezek nem sikerületk), és észrevettem, hogy volt még egy feladatod, az MHEK 1/12, amit itt nem említettél. Ezt is meg fogom nézni, amint az MHEK feladatok ellenőrzéséhez érek.
