### ISSUE TITLE
MH22 feladat

### ISSUE THREAD

**Issue by PaksaiMark** [PE-MK-JAKI-H/MHFGY#57]
Tisztelt Tanár Úr!

Kérem ellenőrizze az MH22-es feladatot.

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.
Ha szeretnél javítni a beadandón, akkor írok egy listát a hiányosságokról.

Megoldásod eltért a feladatgyűjteményben megadottól, de a feladatgyűjtemény volt hibás.

**Comment by PaksaiMark** [comment]
Tisztelt Tanár Úr!
Köszönöm a javítási lehetőséget, de idő hiányában nem élnék vele.
