### ISSUE TITLE
HS10es feladat 

### ISSUE THREAD

**Issue by szeiferta** [PE-MK-JAKI-H/MHFGY#59]
Kedves Tanár úr!

A fent említett feladatra szeretnék ellenőrzést kérni. Illetve először rossz helyre írtam Issues-t(MAFGY-be). Nem tudom,hogyan tudnám törölni de rajta vagyok a dolgon,hogy eltüntessem.
Kérem azt hagyja figyelmen kívül! 

Szeifert Anita

**Comment by Szalay** [comment]
Átnéztem, van néhány javítani való. Ezek egyrészét ide írtam: https://github.com/PE-MK-JAKI-H/MHFGY/commit/417e9302322c2f9bcee70082b9b409139078f851

A többit itt találod: https://github.com/PE-MK-JAKI-H/MHFGY/commit/36ce4a51bcae42fc8c7e8ff531bfb97dc48273de

**Comment by Szalay** [comment]
Ezt az issue-t lezártam, mert nyitottál egy újat.
