### ISSUE TITLE
Hőtan feladatok: HS 33

### ISSUE THREAD

**Issue by muha64** [PE-MK-JAKI-H/MHFGY#6]
![IMG_20200413_100425](https://user-images.githubusercontent.com/63076293/79104387-c4cf0e80-7d6e-11ea-8556-0d449614aee4.jpg)

**Comment by muha64** [comment]
Lehet így két feladatot választani? Illetve a HS 33-nál az egyes számolási lépésekhez tervezek kis magyarázatot írni, de nem tudom hogy az MH 14-hez kellene-e.

**Comment by Szalay** [comment]
1) A HS33 önmagában 100 pontos, nem kell mellé még egy feladat. 
2) A lépéseket természetesen le kell írni, de általában egyenletenként egy mondat elég. 
3) A HS33-nál a számítás menete is rendben van és a számértékek is helyesek.

**Comment by muha64** [comment]
A HS33 sárgával kiemelt +25 pontos ábrázolós részével akadt problémám és azt helyettesítve gondoltam egy másik 25 pontosat választani. Ezt így nem lehet akkor?

**Comment by Szalay** [comment]
A feketével bekeretezett feladatok egybetartoznak.
