### ISSUE TITLE
4/3_MH3_feladat

### ISSUE THREAD

**Issue by tzoltan56** [PE-MK-JAKI-H/MHFGY#60]
Tisztelt Tanár Úr!
Commiteltem az említett két feladatot, de még nem vagyok benne biztos, hogy megfelelő.
Szeretném kikérni a Tanár úr véleményét.
D0EAD9

**Comment by Szalay** [comment]
Az **MH3** rendben van, pontoztam is. Egy hibát találtam, az omega nem a munka jele.

A 4/3-asban maradt néhány hiba, ezeket megjelöltem a forrásban: 
https://github.com/PE-MK-JAKI-H/MHFGY/commit/a66ab44700c33004bc7dc01f268afabb35e39db2
https://github.com/PE-MK-JAKI-H/MHFGY/commit/9cb5b64571a25a5084c9bbd3a8370d04fef71f66

**Comment by Szalay** [comment]
A következő ellenőrzést kérheted itt, nem kell új issue.

**Comment by tzoltan56** [comment]
Tisztelt Tanár úr!
Ha minden igaz sikerült kijavítani a felmerült hibákat, emellet néhány esztétikai javítást is eszközöltem.

**Comment by Szalay** [comment]
Megnéztem újra. A második megegyzésem elkerülte a figyelmed itt: https://github.com/PE-MK-JAKI-H/MHFGY/commit/a66ab44700c33004bc7dc01f268afabb35e39db2

Emellett szintaktikai hibák maradtak a 4/3-as forrásában. Van, ahol lemaradt a sorközi egyenletet záró $, illetve több egyenletben, jellemzően a Q előtt van egy fölösleges {. Ezeket még ki kellene gyomlálni, és ezután 80 % fölött lesz a végeredmény.

**Comment by tzoltan56** [comment]
Bízom benne sikerült megtalálnom, valamint kijavítanom az összes jelzett hibát.
A textit-tel volt egy kis problémám azért nem alkalmaztam korábban a megjegyzés alapján, de most sikerült megoldani.

**Comment by Szalay** [comment]
Frissítettem a táblázatot a végleges értékeléssel.
