### ISSUE TITLE
K1/5. feladat

### ISSUE THREAD

**Issue by CsongediM** [PE-MK-JAKI-H/MHFGY#63]
Tisztelt Tanár Úr!

Feltöltöttem a feladatomat, kérem szépen ellenőrizze.

Köszönettel,
Csöngedi Máté

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítni a beadandón, akkor írok egy listát a hiányosságokról

**Comment by CsongediM** [comment]
Szeretnék javítani a jobb jegyért.

**Comment by Szalay** [comment]
A négyeshez elegendő kijavítani az itt megjelölt hibákat: https://github.com/PE-MK-JAKI-H/MHFGY/commit/4f08e84c0f796dfec1bd7d5fd1da13e1a1e60fd0

Ha esetleg ötöst szeretnél, akkor a p-v diagramot sokkal jobban meg kell csinálni.

**Comment by CsongediM** [comment]
Kijavítottam a hibákat.
Kérem szépen ellenőrizze.

**Comment by Szalay** [comment]
Úgy látom a kisebb hibákat mind kijavítottad. Ennek megfelelően frissítettem a pontozást.
