### ISSUE TITLE
K1/1 és MH25

### ISSUE THREAD

**Issue by Kislovag** [PE-MK-JAKI-H/MHFGY#67]
Tisztelt Tanár Úr!

A címben lévő feladatokat közel elkészítettem, szeretném megkérni Ön-t, hogy ellenőrizze őket, mielőtt leadom (természetesen miután pótlom a hiányos T-s diagramot).  A branch: B00RZ7

Köszönettel,
Kocsor Péter

**Comment by Szalay** [comment]
Elvileg már ellenőriztem és pontoztam is a beadott feladataid, úgyhogy ezt az issue-t csak lezárom.
