### ISSUE TITLE
Feladat eredmény MHFGY

### ISSUE THREAD

**Issue by rupiman97** [PE-MK-JAKI-H/MHFGY#7]
Tanár úr, megtudná esetleg nézni, hogy az I8FMUH branchben a feladatom eredményei jók-e? Köszönöm!

**Comment by Szalay** [comment]
Az egyik korábbi beküldésedhez írtam a megjegyzéseket. Ha nem kapsz értesítést, akkor elvileg ezen a linken megtalálod: https://github.com/PE-MK-JAKI-H/MHFGY/commit/9ccde89c38b31711101b71c056c5c70168e9d4da

Összességében elég jól áll a feladatmegoldásod, már bőven a kettes szint felett van, igaz apróbb hibát találtam sokat, és a számértékeket még nem ellenőriztem. Ha javítottad a most megjelöl hibákat, akkor ismét átnézem.

**Comment by rupiman97** [comment]
Köszönöm szépen! Feltöltöttem a javított verziót. Esetleg azt nem lehet tudni, hogy az elméletnél a túlhevítő nélküli Rankine-Clausius körfolyamat hány pontot fog érni?
