### ISSUE TITLE
5/3 és HS34 feladat (AUKKDP)

### ISSUE THREAD

**Issue by kdaniel97** [PE-MK-JAKI-H/MHFGY#70]
Tisztelt Tanár Úr!
Feltöltöttem a feladataimat:
5/3 Hőterjedés síkfalban
és HS34 Hőcserélő számítása

Köszönettel
Kovács Dániel

**Comment by Szalay** [comment]
Ellenőriztem a feltöltöt feladatokat. Az első probléma az, hogy 125 pontnyi feladatot választottál. A második, hogy a nem a feladatgyűjtemény 5/3-as feladatát oldottad meg. A harmadik, hogy kb. 50 szintaktikai hiba maradt a beadandóban. A HS34 alapvetően rendben volt.

A jelenlegi állapotában a beadandó nem éri el az elégséges szintet, de egy javítási lehetőséged még van, aminek jövő hétfő a határideje. Ha kijavítod a szintaktikai hibákat, akkor a kettes szintet eléred. Ha ennél jobb jegyet szeretnél akkor a valódi 5/3-as feladatot kellene megoldani.

Papeeriában a formázatlan naplófájlból kell kibogarászni, hogy hol vannak a hibák, úgyhogy két képernyőképet csatoltam TeXstudio-ból.

![image](https://user-images.githubusercontent.com/8204804/82933211-e3d5d880-9f89-11ea-9526-e46c51e28f76.png)

![image](https://user-images.githubusercontent.com/8204804/82933373-14b60d80-9f8a-11ea-8f5f-b37553d2dfd7.png)

Mivel bizonyos szintaktikai hibák elrejthetnek más hibákat, ez nem biztos, hogy a teljes lista.
