### ISSUE TITLE
MHFGY/HS16

### ISSUE THREAD

**Issue by SajatJanos** [PE-MK-JAKI-H/MHFGY#71]
Tisztelt Tanár Úr!

Feltöltöttem a saját ágamba (CVSY5R) a feladat leadásra szánt változatát. Van még valamilyen teendőm a leadással kapcsolatban vagy így már leadottnak számít a feladatom?

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítni a beadandón, akkor írok egy listát a hibákról.

**Comment by Szalay** [comment]
Megjelöltem a javítandó dolgokat itt: https://github.com/PE-MK-JAKI-H/MHFGY/commit/cf6d0a00fed7ec94bb856c5792196f3003da623b
