### ISSUE TITLE
7/4 Csőfal hőszigetelésének számítása

### ISSUE THREAD

**Issue by NS9IZH** [PE-MK-JAKI-H/MHFGY#72]
Tisztelt Tanár Úr! 
Feltöltöttem a feladat megoldást.
Tisztelettel
Zelovics Szabolcs
NS9IZH

**Comment by Szalay** [comment]
Átnéztem a beadandót, és sajnos sem tartalmilag, sem megjelenésében, sem technikailag nem elfogadható. A javításra jövő hétfőig van lehetőséged.

Mivel Papeeriában a nyers naplófájlban látod csak a hibákat, ezért egy képernyőképet csatolok:
![image](https://user-images.githubusercontent.com/8204804/82939391-99f1f000-9f93-11ea-8a23-52ff4419481b.png)
