### ISSUE TITLE
K2/5

### ISSUE THREAD

**Issue by Balint12** [PE-MK-JAKI-H/MHFGY#73]
Tisztelt Tanár Úr!
Szeretném kérni a feladatom ellenőrzését.

Tisztelettel:
Vörös Bálint

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

Nem tökéletes, de mivel a jegyen nem változtat, ezért nem javíttatom ki a hibákat. Egyet azért kiemelek: %-kal.

A feladatválasztásoddal is volt probléma, ugyanis ez a feladat már önmagában 100 pont, de ezen felül választottál még egy 50 pontost, az MHEK 22-est.
