### ISSUE TITLE
MHFGY_HS6

### ISSUE THREAD

**Issue by gyananna** [PE-MK-JAKI-H/MHFGY#75]
[MHFGY-master.zip](https://github.com/PE-MK-JAKI-H/MHFGY/files/4678744/MHFGY-master.zip)

**Comment by Szalay** [comment]
A beadást a Moodle-ben leírt módon kérem.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
