### ISSUE TITLE
HS/15 Hűtőház háromrétegű falának hővesztesége

### ISSUE THREAD

**Issue by kazalsoma98** [PE-MK-JAKI-H/MHFGY#77]
Tisztelt Tanár Úr!

Feltöltöttem a kész feladatot a "branch"-embe.

Üdvözlettel: Kazal Soma, FDF83D

**Comment by Szalay** [comment]
Átnéztem, a pontozás eredményét a Google-táblázatbna megtalálod.

CSak egy 75 pontos feladatot választottál, amiből 25 pont az ábrázolás volt, a feltöltött beadandóban viszont nem volt ábra. Így a számításos részt pontosan 100 %-ra kellett volna elkészíteni az elégséges. A pótlásra jövő hétfőig van lehetőséged.
