### ISSUE TITLE
K3/1: Rankine-Clausius körfolyamat termodinamikai hatásfoka

### ISSUE THREAD

**Issue by VeTamas** [PE-MK-JAKI-H/MHFGY#79]
Tisztelt Tanár Úr!

Feltöltöttem a feladatomat a branch-embe.

Tisztelettel,
Vetési Tamás, DJWW2H

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor még jövő hétfőig van lehetőséged. A hármashoz hiányzó 2 pontot a szintaktikai hibák kijavításával is meg tudod szerezni. 
![image](https://user-images.githubusercontent.com/8204804/82944634-d9bcd580-9f9b-11ea-8b7b-bcb3b560218a.png)

**Comment by VeTamas** [comment]
Tisztelt Szalay István!

Elfogadom a jelenlegi pontszámomat, köszönöm szépen.

Tisztelettel,
Vetési Tamás

Szalay <notifications@github.com> ezt írta (időpont: 2020. máj. 26., K,
21:57):
