### ISSUE TITLE
K1/4 megjegyzés

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MHFGY#8]
Jó napot kívánok!

Ha magyarázatként ezeket írom az jó?:

Technikai munka az a munkamennyiség amely egy nyitott rendszerben adott folyamatsor ismételt, ciklikus végrehajtására alkalmas technikai gép működéséhez szükséges.

a)
izotermikus állapotváltozás: ha a hőmérsékletet állandó értéken tartjuk. t=állandó.
fajtérfogat az állapotegyenletből kifejezve:.......
W értéke negatív mert a környezet végez munkát a rendszeren és ezért számolunk lnp1/p2 -vel. Számolhatunk lnp2/p1-gyel viszont akkor az eredmény mínusz egyszeresét kell venni.
b)
adiabatikus állapotváltozás : ha az entrópia állandó. s=állandó, ilyenkor sem hőkölés sem hőelvonás nem történik. 1. főtétel alapján q=0 tehát belsőenergia rovására történik munkavégzés.
c)
politrópikus állapotváltozás: a legtöbb valós folyamatban a nyomás, hőmérséklet, térfogat bevitt vagy elvont hőenergia is változik. "n"politrópikus tényező.
b és c pontokban a számolás azonos módon történik csak a kitevő értékben van különbség. 
A kappa értéke két atomos gáz esetén 1,4 egy atomos gáz esetén 1,3

**Comment by qiseel** [comment]
egy kis korrekció rendszer végez munkát a környezeten

**Comment by Szalay** [comment]
Az első mondtaban a fordított irányr is megkellene említeni. Ha a technikai munka "szükséges", akkor munkagépről van szó, ellenkez őesetben erőgépről. A három alpont rendben van.
