### ISSUE TITLE
I3IHGZ, Botyporus beadandó

### ISSUE THREAD

**Issue by Botyporus** [PE-MK-JAKI-H/MHFGY#80]
A munkámat elvileg beküldtem.

**Comment by Szalay** [comment]
Nem kellett volna saját tárolót csinálni (ez volt a forkolás/elágaztatás), de természetesen így is hozzáférek a beadandódhoz. Ki is igazítottam, csináltam neked egy ágat az MHFGY-n belül.

Pontoztam a jelenlegi állapot alapján. Az eredményt megtalálod a Google-táblázatban.

**Comment by Botyporus** [comment]
A pontom és érdemjegyem véglegesítéséhez kell még valamit csinálnom?

**Comment by Szalay** [comment]
Nem kell már csinálnod semmit. A jegyet a jövő hét folyamán be fogom írn ia Neptunba.
