### ISSUE TITLE
U9AWBY HS38

### ISSUE THREAD

**Issue by Szalay** [PE-MK-JAKI-H/MHFGY#85]

**Comment by Szalay** [comment]
Átnéztem, és van néhány súlyos és nagyon sok kisebb hiba.
1) A megoldásod egy másik feladattal kezdődik.
2) Az ábrákat Tikz-ben kellett volna megrajzolni, vagy legalább megadni, hogy hogyan készültek.

Az apróbb hibákat megjelöltem itt: https://github.com/PE-MK-JAKI-H/MHFGY/commit/d6c8c2da7781f3899e8ced8a6f6735e6c8f20a62

A javítást pedig az MHFGY/U9AWBY ágra kellene feltölteni.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

**Comment by u9awby123** [comment]
Tisztelt Tanár Úr!

Köszönöm szépen az osztályzatot és a gyors átnézést.

Köszönettel Goda Ferenc.





Szalay <notifications@github.com> ezt írta (időpont: 2020. jún. 3., Sze,
18:05):
