### ISSUE TITLE
HS16 javítások-CVSY5R

### ISSUE THREAD

**Issue by SajatJanos** [PE-MK-JAKI-H/MHFGY#86]
Tisztelt Tanár Úr!
Sajnos nem sikerült minden ön által írt hibát kijavítanom de azért feltöltöttem a dokumentum javított változatát amiben ki vannak javítva azok amikkel boldogultam
Köszönettel:
Saját János

**Comment by Szalay** [comment]
Átnéztem újra és frissítettem a pontozást, az eredményt megtalálod a Google-táblázatban.
