### ISSUE TITLE
5/3 és HS34 feladat, javítva (AUKKDP)

### ISSUE THREAD

**Issue by kdaniel97** [PE-MK-JAKI-H/MHFGY#87]
Tisztelt Tanár Úr!
Feltöltöttem a feladataimat:
5/3 Hőterjedés síkfalban
és HS34 Hőcserélő számítása

Ezúttal kidolgoztam az 5/3-as feladatot, és ezenkívül igyekeztem minél több hibát kijavítani

Köszönettel
Kovács Dániel

**Comment by Szalay** [comment]
Még mindig maradt elég sok hiba a beadandóban, de most már eléri az elfogadható szintet. A pontozást megtalálod a Google-táblázatban.
