### ISSUE TITLE
FDF83D HS/15 Ábrák

### ISSUE THREAD

**Issue by kazalsoma98** [PE-MK-JAKI-H/MHFGY#88]
Tisztelt Tanár Úr!

Javítottam a feladatot és adtam hozzá ábrákat. Viszont az ábrák miatt utánaszámoltam a feladatgyűjtemény feladata alatt megoldásokként megadott q-knak, és nem jók, más értéküek mint kiszámolva. A két eredményt is javítottam.

Üdvözlettel: Kazal Soma

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
