### ISSUE TITLE
bjq779

### ISSUE THREAD

**Issue by bevardinora** [PE-MK-JAKI-H/MHFGY#89]
Tisztelt Tanár Úr!

Szeretném ellenőrzésre leadni a feladataimat.

Tisztelettel,
Bévárdi Nóra

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by bevardinora** [comment]
Köszönöm, elfogadom a jegyet.
