### ISSUE TITLE
Hőtan K1/9

### ISSUE THREAD

**Issue by peknora29** [PE-MK-JAKI-H/MHFGY#9]
Tisztelt Tanár Úr! 
A hőtan feladatgyűjtemény 1/9-es feladatát szeretném elkérni.

**Comment by nkrisztina** [comment]
Szia! Küldöm! :)
![93518680_510896846273634_2967429192985083904_n](https://user-images.githubusercontent.com/63298831/79373330-b4798800-7f56-11ea-9005-a3fe7659ed83.jpg)
![93854646_218241532815668_1693445608414642176_n](https://user-images.githubusercontent.com/63298831/79373345-bc392c80-7f56-11ea-8d84-abf59ac7b70d.jpg)

**Comment by peknora29** [comment]
Köszi :)
