### ISSUE TITLE
HS30_LCDOUU_feladatmegoldás

### ISSUE THREAD

**Issue by mayerkira** [PE-MK-JAKI-H/MHFGY#90]
Kérem a feladat ellenőrzését!
Köszönettel:
Mayer Kíra

![HS30_LCDOUU_feladatmegoldás](https://user-images.githubusercontent.com/63208086/84401249-5938de80-ac03-11ea-898b-46ae3ecf3906.jpg)

**Comment by Szalay** [comment]
A számítás rendben van, nem is nagyon volt mit elrontani benne. Az ábrázolásnál viszont a hőmérséklet-hely függvények áltlaános esetben exponenciális függvények, nem egyenesek, és az alakjukat befolyásolja a hőcserélő hőátszármaztatási tényezője, hőátszármaztató felülete és a konvektív vízértékek. Az ábrázoláshoz ezek közül háromnak kell értéket választani, és a negyediket ki kell számolni, hogy illeszkedjen a megadott véghőmérsékletekre.

A vizsgára ne felejts el jelentkezni, mert vizsgajegyként tudom megadni a beadandóra kapott jegyet.
