### ISSUE TITLE
Elkészült beadandó

### ISSUE THREAD

**Issue by mayerkira** [PE-MK-JAKI-H/MHFGY#91]
Tisztelt Tanár Úr!
Szeretném az elkészült HS30_LCDOUU nevű beadandómat ellenőrzésre leadni.
Köszönöm!

Tisztelettel:
Mayer Kíra

**Comment by Szalay** [comment]
Ennyit látok feltöltve: 
![image](https://user-images.githubusercontent.com/8204804/85342280-82524c80-b4ea-11ea-9703-2016fd84c8bc.png)

**Comment by mayerkira** [comment]
A Tanár Úr ezt a tex fájlt nyitotta meg ? Az LCDOUU mappában egy régebbi verzió van amit még nem távolítottam el.

![image](https://user-images.githubusercontent.com/63208086/85370836-a421f280-b52f-11ea-87c2-1c6dee5e466f.png)
