### ISSUE TITLE
A Tanár Úr ezt a tex fájlt nyitotta meg ? Az LCDOUU mappában egy régebbi verzió van amit még nem távolítottam el.

### ISSUE THREAD

**Issue by mayerkira** [PE-MK-JAKI-H/MHFGY#92]
A Tanár Úr ezt a tex fájlt nyitotta meg ? Az LCDOUU mappában egy régebbi verzió van amit még nem távolítottam el.

![image](https://user-images.githubusercontent.com/63208086/85370836-a421f280-b52f-11ea-87c2-1c6dee5e466f.png)

_Originally posted by @mayerkira in https://github.com/PE-MK-JAKI-H/MHFGY/issues/91#issuecomment-647949760_

**Comment by Szalay** [comment]
Átnéztem és pontoztam az alapján, ahogy elvileg ki kellene néznie. Az eredményt megtalálod a Google-táblázatban.
